"use client";

import { useState } from "react";
import type { GeneratedDocumentPayload } from "@/components/safety-intelligence/types";
import { appNativeSelectClassName, ProvenanceBadge } from "@/components/WorkspacePrimitives";

export function DocumentGenerationPanel({
  onGenerate,
  generated,
}: {
  onGenerate: (documentType: string) => Promise<void> | void;
  generated: GeneratedDocumentPayload | null;
}) {
  const [documentType, setDocumentType] = useState("jsa");
  const [working, setWorking] = useState(false);

  return (
    <div>
      <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
        <label className="grid gap-1.5 text-xs font-semibold text-[var(--app-text-strong)]">
          Document type
          <select
            value={documentType}
            onChange={(event) => setDocumentType(event.target.value)}
            className={appNativeSelectClassName}
          >
            <option value="jsa">JSA</option>
            <option value="csep">CSEP</option>
            <option value="peshep">PESHEP</option>
            <option value="pshsep">PSHSEP</option>
            <option value="permit">Permit</option>
            <option value="sop">SOP</option>
            <option value="work_plan">Work plan</option>
            <option value="safety_narrative">Safety narrative</option>
          </select>
        </label>
        <button
          type="button"
          disabled={working}
          onClick={async () => {
            setWorking(true);
            try {
              await onGenerate(documentType);
            } finally {
              setWorking(false);
            }
          }}
          className="rounded-lg bg-[var(--app-accent-primary)] px-3 py-2 text-xs font-semibold text-white disabled:opacity-50"
        >
          {working ? "Generating..." : "Generate draft"}
        </button>
      </div>
      {generated ? (
        <div className="mt-3 grid gap-2">
          <div className="rounded-xl bg-[var(--app-panel)] px-3 py-2.5">
            <div className="flex flex-wrap items-start justify-between gap-2">
              <p className="text-xs font-semibold text-[var(--app-text-strong)]">{generated.document.title}</p>
              <ProvenanceBadge
                kind="ai"
                title="This draft was generated by an AI model from the deterministic rules + conflict context above. Review before sending to the field."
              />
            </div>
            <p className="mt-1 text-xs leading-5 text-[var(--app-text)]">{generated.risk.summary}</p>
          </div>
          {generated.document.sections.slice(0, 3).map((section) => (
            <div key={section.heading} className="rounded-xl border border-[var(--app-border)] bg-white px-3 py-2.5">
              <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[var(--app-text)]">{section.heading}</p>
              <p className="mt-1.5 text-xs leading-5 text-[var(--app-text-strong)]">{section.body}</p>
            </div>
          ))}
        </div>
      ) : null}
    </div>
  );
}
