import type { HseChecklistItem } from "@/lib/compliance/types";

function item(definition: HseChecklistItem): HseChecklistItem {
  return definition;
}

export const HSE_CHECKLIST_ITEMS: HseChecklistItem[] = [
  item({
    id: "baseline-corrective-disciplinary",
    category: "Baseline",
    item: "Corrective action policy and disciplinary process",
    appliesTo: "both",
    requirementType: "always",
    outputSection: "management_systems",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { csep: ["corrective_action_policy_text"], peshep: ["disciplinary_policy_text"] },
    evidenceFields: {
      csep: ["selected_hazards", "tradeItems"],
      peshep: ["scope_of_work_selected", "disciplinary_policy_text"],
    },
  }),
  item({
    id: "baseline-safety-responsibilities",
    category: "Baseline",
    item: "Defined safety responsibilities",
    appliesTo: "both",
    requirementType: "always",
    outputSection: "roles_and_responsibilities",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { csep: ["role_matrix"], peshep: ["role_matrix"] },
    evidenceFields: { csep: ["contractor_company", "contractor_contact"], peshep: ["company_name", "gc_cm"] },
  }),
  item({
    id: "baseline-subcontractor-responsibilities",
    category: "Baseline",
    item: "Subcontractor responsibilities",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "subcontractor_management",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { csep: ["subcontractor_scope_controls"], peshep: ["subcontractor_scope_controls"] },
    triggerMode: "field_truthy",
    triggerFields: { csep: ["gc_cm"], peshep: ["gc_cm"] },
    evidenceFields: { csep: ["gc_cm", "owner_client"], peshep: ["gc_cm", "owner_client"] },
  }),
  item({
    id: "baseline-emergency-response",
    category: "Baseline",
    item: "Emergency response procedures and reporting",
    appliesTo: "both",
    requirementType: "always",
    outputSection: "emergency_response",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { csep: ["emergency_procedures"], peshep: ["emergency_map"] },
    evidenceFields: { csep: ["emergency_procedures"], peshep: ["emergency_map"] },
  }),
  item({
    id: "baseline-incident-investigation",
    category: "Baseline",
    item: "Incident investigation and event management procedures",
    appliesTo: "both",
    requirementType: "always",
    outputSection: "incident_management",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: {
      csep: ["incident_reporting_workflow", "investigation_steps"],
      peshep: ["incident_reporting_process_text"],
    },
    evidenceFields: { csep: ["incident_reporting_workflow"], peshep: ["incident_reporting_process_text"] },
  }),
  item({
    id: "baseline-owner-letter",
    category: "Baseline",
    item: "Owner letter and leadership commitment",
    appliesTo: "peshep",
    requirementType: "always",
    outputSection: "management_systems",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { peshep: ["owner_letter_text"] },
    evidenceFields: { peshep: ["owner_letter_text", "owner_client"] },
  }),
  item({
    id: "baseline-special-conditions-permit",
    category: "Baseline",
    item: "Special conditions permit for approved document variations",
    appliesTo: "peshep",
    requirementType: "always",
    outputSection: "management_systems",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { peshep: ["special_conditions_permit_text"] },
    evidenceFields: { peshep: ["special_conditions_permit_text"] },
  }),
  item({
    id: "baseline-assumed-trades-index",
    category: "Baseline",
    item: "Assumed trades index and coordination assumptions",
    appliesTo: "peshep",
    requirementType: "always",
    outputSection: "trade_coordination",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { peshep: ["assumed_trades_index"] },
    evidenceFields: { peshep: ["assumed_trades_index", "scope_of_work_selected"] },
  }),
  item({
    id: "baseline-hazcom-ghs",
    category: "Baseline",
    item: "Hazard communication and GHS program",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "hazcom_ghs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["chemical", "hazmat", "ghs", "sds", "solvent", "coating"],
    evidenceFields: { csep: ["selected_hazards", "additional_permits"], peshep: ["permits_selected"] },
  }),
  item({
    id: "baseline-hse-orientation",
    category: "Baseline",
    item: "HSE orientation",
    appliesTo: "both",
    requirementType: "always",
    outputSection: "orientation_training",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    evidenceFields: { csep: ["site_specific_notes"], peshep: ["orientation_required", "orientation_pass_score"] },
  }),
  item({
    id: "baseline-ppe-requirements",
    category: "Baseline",
    item: "PPE requirements, selection, and training",
    appliesTo: "both",
    requirementType: "always",
    outputSection: "ppe_program",
    aiAction: "draft",
    requiredUserConfirmation: false,
    manualReviewDefault: false,
    requiredFields: { csep: ["required_ppe"], peshep: ["required_ppe"] },
    evidenceFields: { csep: ["required_ppe"], peshep: ["permits_selected", "scope_of_work_selected"] },
  }),
  item({
    id: "baseline-self-inspections",
    category: "Baseline",
    item: "Documented self-inspections and observation tracking",
    appliesTo: "both",
    requirementType: "always",
    outputSection: "inspections_observations",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: {
      csep: ["inspection_frequency", "observation_log_method", "closure_workflow"],
      peshep: ["inspection_frequency", "observation_log_method", "closure_workflow"],
    },
  }),
  item({
    id: "company-formal-policy",
    category: "CompanyPolicy",
    item: "Formal safety policy statement",
    appliesTo: "both",
    requirementType: "always",
    outputSection: "company_policy",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { csep: ["formal_safety_policy_text"], peshep: ["formal_safety_policy_text"] },
  }),
  item({
    id: "company-planning-jha-sop",
    category: "CompanyPolicy",
    item: "Safety planning / JHA / SOP process",
    appliesTo: "both",
    requirementType: "always",
    outputSection: "planning_methodology",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    evidenceFields: { csep: ["tasks", "scope_of_work"], peshep: ["scope_of_work_selected", "project_description"] },
  }),
  item({
    id: "company-leadership-training",
    category: "CompanyPolicy",
    item: "Leadership safety training",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "leadership_training",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    evidenceFields: {
      csep: ["site_specific_notes"],
      peshep: ["requires_osha30_pm_super_within_5yrs", "requires_osha30_supervisor_on_site"],
    },
  }),
  item({
    id: "company-safety-meetings",
    category: "CompanyPolicy",
    item: "Required workplace safety meetings",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "meetings_communications",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { csep: ["safety_meeting_cadence"], peshep: ["safety_meeting_cadence"] },
  }),
  item({
    id: "company-return-to-work",
    category: "CompanyPolicy",
    item: "Return-to-work / light duty policy",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "return_to_work",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { csep: ["return_to_work_policy"], peshep: ["return_to_work_policy"] },
  }),
  item({
    id: "company-substance-abuse",
    category: "CompanyPolicy",
    item: "Substance abuse / drug free workforce policy",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "substance_abuse_policy",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "field_truthy",
    triggerFields: { peshep: ["requires_drug_card_ccs"] },
    evidenceFields: { peshep: ["requires_drug_card_ccs"], csep: ["site_specific_notes"] },
  }),
  item({
    id: "company-occupational-physician",
    category: "CompanyPolicy",
    item: "Designated occupational physician or facility",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "medical_designation",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    evidenceFields: { peshep: ["emergency_map"], csep: ["emergency_procedures"] },
  }),
  item({
    id: "company-safety-culture",
    category: "CompanyPolicy",
    item: "Safety culture improvement content",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "culture_improvement",
    aiAction: "draft",
    requiredUserConfirmation: false,
    manualReviewDefault: false,
    requiredFields: { csep: ["safety_culture_goals"], peshep: ["safety_culture_goals"] },
  }),
  item({
    id: "company-safety-capacity",
    category: "CompanyPolicy",
    item: "Safety capacity extra credit areas like full-time safety director",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "staffing_capacity",
    aiAction: "manual_review",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { csep: ["safety_director_name"], peshep: ["safety_director_name"] },
  }),
  item({
    id: "work-hse-asbestos-awareness",
    category: "WorkSpecificHSE",
    item: "Asbestos awareness",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "regulatory_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["asbestos", "abatement", "pipe insulation"],
  }),
  item({
    id: "work-hse-asbestos-handling",
    category: "WorkSpecificHSE",
    item: "Asbestos handling/removal",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "regulatory_programs",
    aiAction: "manual_review",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["asbestos removal", "abatement", "friable", "encapsulation"],
  }),
  item({
    id: "work-hse-bloodborne-pathogens",
    category: "WorkSpecificHSE",
    item: "Bloodborne pathogens",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "regulatory_programs",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["bloodborne", "medical", "biohazard", "first aid exposure"],
  }),
  item({
    id: "work-hse-compressed-cylinders",
    category: "WorkSpecificHSE",
    item: "Compressed cylinder handling/storage",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "regulatory_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["weld", "cutting", "oxygen", "acetylene", "compressed gas"],
  }),
  item({
    id: "work-hse-confined-space",
    category: "WorkSpecificHSE",
    item: "Confined space entry",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "permit_and_entry_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["confined space"],
    evidenceFields: { csep: ["additional_permits"], peshep: ["permits_selected", "scope_of_work_selected"] },
  }),
  item({
    id: "work-hse-construction-confined-space",
    category: "WorkSpecificHSE",
    item: "Construction confined space entry",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "permit_and_entry_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["construction confined space", "permit-required confined space"],
  }),
  item({
    id: "work-hse-crane-rigging",
    category: "WorkSpecificHSE",
    item: "Crane and rigging",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "lifting_and_rigging",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["crane", "rigging", "critical lift", "hoist"],
    evidenceFields: { csep: ["tasks", "selected_hazards"], peshep: ["permits_selected", "lift_plans_required"] },
  }),
  item({
    id: "work-hse-electrical",
    category: "WorkSpecificHSE",
    item: "Electrical safety",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "electrical_loto",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["electrical", "energized", "loto", "line break"],
  }),
  item({
    id: "work-hse-fall-protection",
    category: "WorkSpecificHSE",
    item: "Fall protection",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "fall_protection",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["work at height", "fall", "ladder", "scaffold", "mewp", "awp"],
  }),
  item({
    id: "work-hse-fire-prevention",
    category: "WorkSpecificHSE",
    item: "Fire prevention",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "fire_prevention",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["hot work", "welding", "cutting", "spark"],
  }),
  item({
    id: "work-hse-forklift-pit",
    category: "WorkSpecificHSE",
    item: "Forklift / powered industrial truck",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "equipment_operations",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["forklift", "material handling", "pit"],
  }),
  item({
    id: "work-hse-tools",
    category: "WorkSpecificHSE",
    item: "Hand and power tools",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "tool_safety",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["tool", "drill", "grinder", "saw"],
  }),
  item({
    id: "work-hse-hearing",
    category: "WorkSpecificHSE",
    item: "Hearing conservation",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "occupational_health",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["hearing", "noise", "grinding", "hammering"],
  }),
  item({
    id: "work-hse-housekeeping",
    category: "WorkSpecificHSE",
    item: "Housekeeping",
    appliesTo: "both",
    requirementType: "always",
    outputSection: "housekeeping",
    aiAction: "draft",
    requiredUserConfirmation: false,
    manualReviewDefault: false,
  }),
  item({
    id: "work-hse-ladder",
    category: "WorkSpecificHSE",
    item: "Ladder safety",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "access_safety",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["ladder", "work at height"],
  }),
  item({
    id: "work-hse-lead",
    category: "WorkSpecificHSE",
    item: "Lead handling/removal",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "regulatory_programs",
    aiAction: "manual_review",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["lead", "lead paint", "pb"],
  }),
  item({
    id: "work-hse-loto",
    category: "WorkSpecificHSE",
    item: "Lockout/tagout",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "electrical_loto",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["loto", "lockout", "tagout", "energized"],
  }),
  item({
    id: "work-hse-awp",
    category: "WorkSpecificHSE",
    item: "AWP / manlift / scissor lift",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "access_equipment",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["mewp", "awp", "manlift", "scissor lift", "aerial lift"],
  }),
  item({
    id: "work-hse-language",
    category: "WorkSpecificHSE",
    item: "Workforce language and translation requirements",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "communication_controls",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    requiredFields: { csep: ["workforce_languages"], peshep: ["workforce_languages"] },
  }),
  item({
    id: "work-hse-powder-actuated",
    category: "WorkSpecificHSE",
    item: "Powder actuated tools",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "tool_safety",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["powder actuated", "hilti", "shot-fired"],
  }),
  item({
    id: "work-hse-radiation",
    category: "WorkSpecificHSE",
    item: "Radiation",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "specialized_hazards",
    aiAction: "manual_review",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["radiation", "x-ray", "nuclear", "radioactive"],
  }),
  item({
    id: "work-hse-respiratory",
    category: "WorkSpecificHSE",
    item: "Respiratory protection",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "occupational_health",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["respirator", "silica", "dust", "fume", "asbestos"],
  }),
  item({
    id: "work-hse-scaffold",
    category: "WorkSpecificHSE",
    item: "Scaffolding",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "access_safety",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["scaffold", "scaffolds"],
  }),
  item({
    id: "work-hse-osha10-supervisor",
    category: "WorkSpecificHSE",
    item: "OSHA 10 supervisor training",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "training_requirements",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    evidenceFields: {
      peshep: ["requires_osha10", "requires_osha30_pm_super_within_5yrs", "requires_osha30_supervisor_on_site"],
      csep: ["site_specific_notes"],
    },
  }),
  item({
    id: "work-hse-trenching",
    category: "WorkSpecificHSE",
    item: "Trenching/excavation",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "excavation_ground_disturbance",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["trench", "excavat", "ground disturb", "groundbreaking", "ground breaking"],
  }),
  item({
    id: "work-hse-welding-cutting",
    category: "WorkSpecificHSE",
    item: "Welding and cutting",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "hot_work_program",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["weld", "cutting", "hot work"],
  }),
  item({
    id: "env-general-chemical",
    category: "EnvGeneral",
    item: "Hazardous chemical handling",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "environmental_general_controls",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["chemical", "hazmat", "solvent", "coating"],
  }),
  item({
    id: "env-general-swppp",
    category: "EnvGeneral",
    item: "SWPPP / storm water quality construction controls",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "environmental_general_controls",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["swppp", "storm water", "stormwater", "erosion", "sediment", "outdoor"],
  }),
  item({
    id: "env-general-spill",
    category: "EnvGeneral",
    item: "Spill control and clean-up",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "environmental_general_controls",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["spill", "chemical", "fuel", "hydraulic"],
  }),
  item({
    id: "env-general-regulated-waste",
    category: "EnvGeneral",
    item: "Regulated waste management",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "environmental_general_controls",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["waste", "hazardous waste", "disposal", "rcra"],
  }),
  item({
    id: "env-reg-asbestos-control",
    category: "EnvRegulatory",
    item: "Asbestos control",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "environmental_regulatory_programs",
    aiAction: "manual_review",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["asbestos", "abatement"],
  }),
  item({
    id: "env-reg-drinking-water",
    category: "EnvRegulatory",
    item: "Drinking water systems",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "environmental_regulatory_programs",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["drinking water", "potable", "water system"],
  }),
  item({
    id: "env-reg-audit",
    category: "EnvRegulatory",
    item: "Environmental compliance auditing",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "environmental_regulatory_programs",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
  }),
  item({
    id: "env-reg-air-permit",
    category: "EnvRegulatory",
    item: "Air permitting",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "environmental_regulatory_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["air permit", "emission", "coating", "weld", "dust"],
  }),
  item({
    id: "env-reg-water-permit",
    category: "EnvRegulatory",
    item: "Water permitting",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "environmental_regulatory_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["water discharge", "dewatering", "drainage"],
  }),
  item({
    id: "env-reg-hazmat-shipping",
    category: "EnvRegulatory",
    item: "Hazardous material packaging and shipping",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "environmental_regulatory_programs",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["shipping", "dot", "hazmat package"],
  }),
  item({
    id: "env-reg-rcra",
    category: "EnvRegulatory",
    item: "Hazardous waste / RCRA-type controls",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "environmental_regulatory_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["rcra", "hazardous waste", "waste profile"],
  }),
  item({
    id: "env-reg-fifra",
    category: "EnvRegulatory",
    item: "FIFRA / pesticide application",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "environmental_regulatory_programs",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["pesticide", "fifra", "herbicide"],
  }),
  item({
    id: "env-reg-land-application",
    category: "EnvRegulatory",
    item: "Land application of materials",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "environmental_regulatory_programs",
    aiAction: "recommend",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["land application", "biosolids", "soil amendment"],
  }),
  item({
    id: "env-reg-lead-paint",
    category: "EnvRegulatory",
    item: "Lead based paint",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "environmental_regulatory_programs",
    aiAction: "manual_review",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["lead paint", "lead abatement", "pb"],
  }),
  item({
    id: "env-reg-leak-detection",
    category: "EnvRegulatory",
    item: "Leak detection and repair",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "environmental_regulatory_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["leak", "fugitive emission", "repair"],
  }),
  item({
    id: "env-reg-backflow",
    category: "EnvRegulatory",
    item: "Potable water backflow prevention",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "environmental_regulatory_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["backflow", "potable", "cross connection", "plumbing"],
  }),
  item({
    id: "env-reg-radiation-waste",
    category: "EnvRegulatory",
    item: "Radiation waste management",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "environmental_regulatory_programs",
    aiAction: "manual_review",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["radiation waste", "radioactive"],
  }),
  item({
    id: "env-reg-refrigerants",
    category: "EnvRegulatory",
    item: "Refrigerants",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "environmental_regulatory_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["hvac", "refrigerant", "freon", "chiller"],
  }),
  item({
    id: "env-reg-remediation",
    category: "EnvRegulatory",
    item: "Soil or groundwater remediation",
    appliesTo: "both",
    requirementType: "conditional",
    outputSection: "environmental_regulatory_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["remediation", "soil", "groundwater", "excavat"],
  }),
  item({
    id: "env-reg-industrial-storm-water",
    category: "EnvRegulatory",
    item: "Industrial storm water",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "environmental_regulatory_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["industrial storm water", "stormwater", "outdoor storage"],
  }),
  item({
    id: "env-reg-wastewater",
    category: "EnvRegulatory",
    item: "Wastewater management",
    appliesTo: "both",
    requirementType: "project_specific",
    outputSection: "environmental_regulatory_programs",
    aiAction: "draft",
    requiredUserConfirmation: true,
    manualReviewDefault: true,
    triggerMode: "keyword_any",
    triggerKeywords: ["wastewater", "discharge", "effluent", "sewer"],
  }),
];

export function getChecklistItemsForSurface(surface: "csep" | "peshep") {
  return HSE_CHECKLIST_ITEMS.filter((entry) => entry.appliesTo === "both" || entry.appliesTo === surface);
}
