create table if not exists public.injury_forecast_audit_log (
  id uuid primary key default gen_random_uuid(),
  company_id uuid null references public.companies(id) on delete set null,
  jobsite_id uuid null references public.company_jobsites(id) on delete set null,
  generated_at timestamptz not null default now(),
  forecast_month text not null,
  model_version text not null,
  risk_level text not null,
  confidence_score numeric not null,
  included_record_count integer not null default 0,
  excluded_record_count integer not null default 0,
  source_mix jsonb not null default '{}'::jsonb,
  trust_mix jsonb not null default '{}'::jsonb,
  exclusion_reasons jsonb not null default '{}'::jsonb,
  forecast_integrity jsonb not null default '{}'::jsonb,
  recommended_controls jsonb not null default '[]'::jsonb,
  reviewed_by uuid null references auth.users(id) on delete set null,
  final_human_decision text null,
  post_review_changes jsonb not null default '{}'::jsonb
);