-- Interactive AI Risk Action Loop: typed follow-up actions and conservative mitigation credit.

alter table public.company_risk_ai_recommendations
  add column if not exists action_type text not null default 'assign';

alter table public.company_risk_ai_recommendations
  add column if not exists linked_module text null;

alter table public.company_risk_ai_recommendations
  add column if not exists linked_record_id uuid null;

alter table public.company_risk_ai_recommendations
  add column if not exists verification_required boolean not null default true;

alter table public.company_risk_ai_recommendations
  add column if not exists mitigation_state text not null default 'unverified';

alter table public.company_risk_ai_recommendations
  add column if not exists risk_reduction_points integer not null default 0;

alter table public.company_risk_ai_recommendations
  drop constraint if exists company_risk_ai_recommendations_action_type_check;

alter table public.company_risk_ai_recommendations
  add constraint company_risk_ai_recommendations_action_type_check check (
    action_type in (
      'assign',
      'request_documentation',
      'request_inspection',
      'create_corrective_action',
      'request_permit',
      'accountability_review',
      'stop_work_review'
    )
  );

alter table public.company_risk_ai_recommendations
  drop constraint if exists company_risk_ai_recommendations_linked_module_check;

alter table public.company_risk_ai_recommendations
  add constraint company_risk_ai_recommendations_linked_module_check check (
    linked_module is null
    or linked_module in (
      'risk_recommendation',
      'corrective_action',
      'permit',
      'auditflow_assignment',
      'documentation_request',
      'accountability_review',
      'stop_work_review'
    )
  );

alter table public.company_risk_ai_recommendations
  drop constraint if exists company_risk_ai_recommendations_mitigation_state_check;

alter table public.company_risk_ai_recommendations
  add constraint company_risk_ai_recommendations_mitigation_state_check check (
    mitigation_state in (
      'unverified',
      'assigned',
      'documentation_requested',
      'inspection_requested',
      'linked_action_created',
      'evidence_uploaded',
      'field_verified',
      'resolved',
      'dismissed'
    )
  );

alter table public.company_risk_ai_recommendations
  drop constraint if exists company_risk_ai_recommendations_risk_reduction_points_check;

alter table public.company_risk_ai_recommendations
  add constraint company_risk_ai_recommendations_risk_reduction_points_check check (
    risk_reduction_points >= 0 and risk_reduction_points <= 25
  );

create index if not exists company_risk_ai_recommendations_action_type_idx
  on public.company_risk_ai_recommendations (company_id, action_type, mitigation_state, created_at desc);

alter table public.company_risk_recommendation_events
  drop constraint if exists company_risk_recommendation_events_event_type_check;

alter table public.company_risk_recommendation_events
  add constraint company_risk_recommendation_events_event_type_check check (
    event_type in (
      'created',
      'accepted',
      'assigned',
      'field_used',
      'resolved',
      'dismissed',
      'feedback',
      'documentation_requested',
      'inspection_requested',
      'corrective_action_created',
      'permit_requested',
      'accountability_review_requested',
      'stop_work_review_requested'
    )
  );

comment on column public.company_risk_ai_recommendations.action_type is
  'Suggested supervisor follow-up action generated by deterministic rules or AI.';

comment on column public.company_risk_ai_recommendations.mitigation_state is
  'Conservative follow-through state used to decide whether risk reduction credit can be shown.';

comment on column public.company_risk_ai_recommendations.risk_reduction_points is
  'Deterministic mitigation credit. Generated or assigned actions remain 0 until field use or resolution is verified.';
