import { enforceDraftOnlyStatus, requireHumanReview } from "@/lib/gus/gusSafetyGate";
import type { GusPlanStatus } from "@/lib/gus/gusTypes";
import { validateGusOutput } from "@/lib/gus/gusValidation";

export const GUS_DRAFT_REVIEW_NOTICE = "Generated by Gus AI Safety Coach — Requires human review.";

export type GusDraftRecordType = "jsa" | "permit_checklist" | "pretask_briefing";

export type GusPlanningSessionRecord = {
  id: string;
  company_id?: string | null;
  jobsite_id?: string | null;
  user_id?: string | null;
  work_type: string;
  detected_modules?: unknown;
  task_description?: string | null;
  status?: string | null;
  plan_data?: unknown;
  missing_items?: unknown;
  risk_flags?: unknown;
  human_review_required?: boolean | null;
};

export type GusDraftJsaContent = {
  notice: typeof GUS_DRAFT_REVIEW_NOTICE;
  planningSessionId: string;
  draftOnly: true;
  humanReviewRequired: true;
  officialRecordCreated: false;
  status: GusPlanStatus;
  task: string;
  steps: string[];
  hazards: string[];
  controls: string[];
  requiredPermits: string[];
  requiredTraining: string[];
  inspections: string[];
  ppe: string[];
  stopWorkTriggers: string[];
  missingInformation: string[];
  reviewerRequired: string[];
  riskFlags: string[];
};

export type GusDraftPermitChecklistContent = {
  notice: typeof GUS_DRAFT_REVIEW_NOTICE;
  planningSessionId: string;
  draftOnly: true;
  humanReviewRequired: true;
  officialRecordCreated: false;
  status: GusPlanStatus;
  permitType: string;
  triggerReason: string;
  requiredReviewItems: string[];
  missingInformation: string[];
  requiredSignaturesReviewers: string[];
  riskFlags: string[];
};

export type GusPreTaskBriefingContent = {
  notice: typeof GUS_DRAFT_REVIEW_NOTICE;
  planningSessionId: string;
  draftOnly: true;
  humanReviewRequired: true;
  officialRecordCreated: false;
  status: GusPlanStatus;
  taskSummary: string;
  keyHazards: string[];
  controls: string[];
  crewTalkingPoints: string[];
  stopWorkTriggers: string[];
  emergencyConsiderations: string[];
  crewQuestions: string[];
  missingInformation: string[];
  reviewerRequired: string[];
  riskFlags: string[];
};

export type GusDraftRecordContent =
  | GusDraftJsaContent
  | GusDraftPermitChecklistContent
  | GusPreTaskBriefingContent;

export type GusDraftRecordBuildResult = {
  planType: GusDraftRecordType;
  planTitle: string;
  status: GusPlanStatus;
  content: GusDraftRecordContent;
  validationFindings: ReturnType<typeof validateGusOutput<GusDraftRecordContent>>["findings"];
};

type PlanSection = {
  title?: unknown;
  items?: unknown;
};

type NormalizedPlanData = {
  taskSummary: string;
  sections: PlanSection[];
  hazards: string[];
  controls: string[];
  permits: string[];
  training: string[];
  inspections: string[];
  ppe: string[];
  stopWorkTriggers: string[];
  emergencyConsiderations: string[];
  talkingPoints: string[];
  reviewers: string[];
  missingInformation: string[];
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function text(value: unknown) {
  return typeof value === "string" ? value.trim() : "";
}

function textArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.map(text).filter(Boolean);
}

function unique(values: Array<string | undefined | null>) {
  return Array.from(new Set(values.map((value) => value?.trim()).filter((value): value is string => Boolean(value))));
}

function sectionItems(plan: NormalizedPlanData, title: string) {
  const section = plan.sections.find((item) => text(item.title).toLowerCase() === title.toLowerCase());
  return textArray(section?.items);
}

function normalizePlanData(session: GusPlanningSessionRecord): NormalizedPlanData {
  const planData = isRecord(session.plan_data) ? session.plan_data : {};
  const sections = Array.isArray(planData.sections) ? (planData.sections as PlanSection[]) : [];

  const base: NormalizedPlanData = {
    taskSummary: text(planData.summary) || text(planData.title) || text(session.task_description) || "Task needs human review.",
    sections,
    hazards: textArray(planData.hazards),
    controls: textArray(planData.controls),
    permits: textArray(planData.possiblePermits),
    training: textArray(planData.possibleTraining),
    inspections: textArray(planData.preStartInspections),
    ppe: textArray(planData.ppe),
    stopWorkTriggers: textArray(planData.stopWorkTriggers),
    emergencyConsiderations: textArray(planData.emergencyResponseConsiderations),
    talkingPoints: textArray(planData.crewTalkingPoints),
    reviewers: textArray(planData.requiredReviewers),
    missingInformation: textArray(planData.missingInformation),
  };

  return {
    ...base,
    taskSummary: sectionItems(base, "Task Summary")[0] || base.taskSummary,
    hazards: unique([...base.hazards, ...sectionItems(base, "Primary Hazards")]),
    controls: unique([...base.controls, ...sectionItems(base, "Required Controls")]),
    permits: unique([...base.permits, ...sectionItems(base, "Required Permits / Reviews")]),
    training: unique([...base.training, ...sectionItems(base, "Required Training / Qualifications")]),
    inspections: unique([...base.inspections, ...sectionItems(base, "Inspection Requirements")]),
    ppe: unique([...base.ppe, ...sectionItems(base, "PPE")]),
    stopWorkTriggers: unique([...base.stopWorkTriggers, ...sectionItems(base, "Stop-Work Triggers")]),
    emergencyConsiderations: unique([
      ...base.emergencyConsiderations,
      ...sectionItems(base, "Emergency Response Considerations"),
    ]),
    talkingPoints: unique([...base.talkingPoints, ...sectionItems(base, "Pre-Task Briefing Talking Points")]),
    reviewers: unique([...base.reviewers, ...sectionItems(base, "Human Review Required")]),
    missingInformation: unique([...base.missingInformation, ...sectionItems(base, "Missing Information")]),
  };
}

function sessionMissingItems(session: GusPlanningSessionRecord, plan: NormalizedPlanData) {
  return unique([...textArray(session.missing_items), ...plan.missingInformation]);
}

function statusForDraft(session: GusPlanningSessionRecord, missingInformation: string[]) {
  if (missingInformation.length > 0) return "draft_incomplete" satisfies GusPlanStatus;
  return enforceDraftOnlyStatus(session.status ?? "draft_ready_for_review");
}

function fallbackItems(items: string[], fallback: string) {
  return items.length > 0 ? items : [fallback];
}

function finalReviewers(reviewers: string[]) {
  return fallbackItems(reviewers, "Supervisor or authorized safety representative review required.");
}

function draftSteps(plan: NormalizedPlanData) {
  return fallbackItems(
    plan.talkingPoints.length > 0
      ? plan.talkingPoints
      : [
          "Review task scope with the crew.",
          "Review hazards, controls, permits, training, inspections, PPE, and stop-work triggers.",
          "Route this draft for the required human review before work starts.",
        ],
    "Planning steps need human review.",
  );
}

function validateDraft(content: GusDraftRecordContent) {
  const reviewed = requireHumanReview(content);
  const validation = validateGusOutput<GusDraftRecordContent>(reviewed);
  return {
    content: validation.sanitizedOutput,
    validationFindings: validation.findings,
  };
}

export function buildGusDraftJsa(session: GusPlanningSessionRecord): GusDraftRecordBuildResult {
  const plan = normalizePlanData(session);
  const missingInformation = sessionMissingItems(session, plan);
  const status = statusForDraft(session, missingInformation);
  const content: GusDraftJsaContent = {
    notice: GUS_DRAFT_REVIEW_NOTICE,
    planningSessionId: session.id,
    draftOnly: true,
    humanReviewRequired: true,
    officialRecordCreated: false,
    status,
    task: plan.taskSummary,
    steps: draftSteps(plan),
    hazards: fallbackItems(plan.hazards, "Hazards need human review."),
    controls: fallbackItems(plan.controls, "Controls need human review."),
    requiredPermits: fallbackItems(plan.permits, "Permit needs must be verified against company policy."),
    requiredTraining: fallbackItems(plan.training, "Training and qualification needs must be verified."),
    inspections: fallbackItems(plan.inspections, "Inspection needs must be verified before work starts."),
    ppe: fallbackItems(plan.ppe, "PPE selection needs human review."),
    stopWorkTriggers: fallbackItems(plan.stopWorkTriggers, "Stop-work triggers need human review."),
    missingInformation,
    reviewerRequired: finalReviewers(plan.reviewers),
    riskFlags: textArray(session.risk_flags),
  };
  const validation = validateDraft(content);

  return {
    planType: "jsa",
    planTitle: `Draft JSA: ${plan.taskSummary}`,
    status,
    content: validation.content,
    validationFindings: validation.validationFindings,
  };
}

export function buildGusDraftPermitChecklist(
  session: GusPlanningSessionRecord,
  options: { permitType?: string } = {},
): GusDraftRecordBuildResult {
  const plan = normalizePlanData(session);
  const missingInformation = sessionMissingItems(session, plan);
  const status = statusForDraft(session, missingInformation);
  const permitType = text(options.permitType) || plan.permits[0] || "Permit review needed";
  const content: GusDraftPermitChecklistContent = {
    notice: GUS_DRAFT_REVIEW_NOTICE,
    planningSessionId: session.id,
    draftOnly: true,
    humanReviewRequired: true,
    officialRecordCreated: false,
    status,
    permitType,
    triggerReason: `Planning session identified ${permitType} as needing review before work starts.`,
    requiredReviewItems: fallbackItems(
      unique([...plan.permits, ...plan.inspections, ...plan.controls.slice(0, 6)]),
      "Permit review items need human review.",
    ),
    missingInformation,
    requiredSignaturesReviewers: finalReviewers(plan.reviewers),
    riskFlags: textArray(session.risk_flags),
  };
  const validation = validateDraft(content);

  return {
    planType: "permit_checklist",
    planTitle: `Draft Permit Checklist: ${permitType}`,
    status,
    content: validation.content,
    validationFindings: validation.validationFindings,
  };
}

export function buildGusPreTaskBriefing(session: GusPlanningSessionRecord): GusDraftRecordBuildResult {
  const plan = normalizePlanData(session);
  const missingInformation = sessionMissingItems(session, plan);
  const status = statusForDraft(session, missingInformation);
  const content: GusPreTaskBriefingContent = {
    notice: GUS_DRAFT_REVIEW_NOTICE,
    planningSessionId: session.id,
    draftOnly: true,
    humanReviewRequired: true,
    officialRecordCreated: false,
    status,
    taskSummary: plan.taskSummary,
    keyHazards: fallbackItems(plan.hazards, "Key hazards need human review."),
    controls: fallbackItems(plan.controls, "Controls need human review."),
    crewTalkingPoints: draftSteps(plan),
    stopWorkTriggers: fallbackItems(plan.stopWorkTriggers, "Stop-work triggers need human review."),
    emergencyConsiderations: fallbackItems(
      plan.emergencyConsiderations,
      "Emergency access, communication, and escalation contacts need human review.",
    ),
    crewQuestions: [
      "Does every crew member understand the task scope and limits?",
      "What hazards or changing conditions are missing from this draft?",
      "Who will stop work and escalate if a trigger appears?",
    ],
    missingInformation,
    reviewerRequired: finalReviewers(plan.reviewers),
    riskFlags: textArray(session.risk_flags),
  };
  const validation = validateDraft(content);

  return {
    planType: "pretask_briefing",
    planTitle: `Draft Pre-Task Briefing: ${plan.taskSummary}`,
    status,
    content: validation.content,
    validationFindings: validation.validationFindings,
  };
}

export function buildGusDraftRecord(
  session: GusPlanningSessionRecord,
  type: GusDraftRecordType,
  options: { permitType?: string } = {},
) {
  if (type === "jsa") return buildGusDraftJsa(session);
  if (type === "permit_checklist") return buildGusDraftPermitChecklist(session, options);
  return buildGusPreTaskBriefing(session);
}
