export const TERMS_VERSION = "v1.0";

export const CLICKWRAP_LABEL =
  "I agree to the Terms of Service, Liability Waiver, and Licensing Agreement";

export const DOWNLOAD_CONFIRMATION_LABEL =
  "I confirm I have reviewed and accept responsibility for this document";

export const DOCUMENT_DISCLAIMER_LINES = [
  "DISCLAIMER:",
  "This document was generated by Safety360Docs and is for informational purposes only.",
  "The user is solely responsible for verifying accuracy, ensuring compliance, and implementing all safety measures.",
  "Safety360Docs is not liable for any injury, death, damages, or regulatory violations resulting from use of this document.",
] as const;

export function isCurrentTermsVersion(termsVersion?: string | null) {
  return (termsVersion ?? "").trim() === TERMS_VERSION;
}

export type UserAgreementRecord = {
  user_id: string;
  accepted_terms: boolean;
  accepted_at: string;
  ip_address: string | null;
  terms_version: string;
};

export type AgreementSection = {
  heading: string;
  body: string;
};

export type AgreementSectionGroup = {
  title: string;
  sections: AgreementSection[];
};

export type AgreementConfig = {
  version: string;
  termsOfService: AgreementSectionGroup;
  liabilityWaiver: AgreementSectionGroup;
};

type MessageError = { message?: string | null };

type SupabaseLikeClient = {
  from: (table: string) => unknown;
  auth?: {
    admin?: {
      getUserById: (userId: string) => PromiseLike<{
        data: { user?: { user_metadata?: Record<string, unknown> | null } | null };
        error: MessageError | null;
      }>;
      updateUserById: (
        userId: string,
        attributes: { user_metadata: Record<string, unknown> }
      ) => PromiseLike<{ data: unknown; error: MessageError | null }>;
    };
  };
};

function isMissingAgreementTableError(error?: { message?: string | null } | null) {
  const message = (error?.message ?? "").toLowerCase();

  return (
    message.includes("user_agreements") &&
    (message.includes("schema cache") || message.includes("does not exist"))
  );
}

function parseAgreementFromMetadata(userId: string, metadata: Record<string, unknown> | undefined) {
  if (!metadata || metadata.accepted_terms !== true) {
    return null;
  }

  return {
    user_id: userId,
    accepted_terms: true,
    accepted_at:
      typeof metadata.accepted_at === "string"
        ? metadata.accepted_at
        : new Date().toISOString(),
    ip_address:
      typeof metadata.accepted_terms_ip === "string"
        ? metadata.accepted_terms_ip
        : null,
    terms_version:
      typeof metadata.terms_version === "string"
        ? metadata.terms_version
        : TERMS_VERSION,
  } satisfies UserAgreementRecord;
}

export function getClientIpAddress(request: Request) {
  const forwardedFor = request.headers.get("x-forwarded-for");
  if (forwardedFor) {
    return forwardedFor.split(",")[0]?.trim() || null;
  }

  const realIp = request.headers.get("x-real-ip");
  return realIp?.trim() || null;
}

export function buildAgreementAcceptance(params: {
  userId: string;
  ipAddress?: string | null;
  termsVersion?: string;
}) {
  return {
    user_id: params.userId,
    accepted_terms: true,
    accepted_at: new Date().toISOString(),
    ip_address: params.ipAddress ?? null,
    terms_version: params.termsVersion ?? TERMS_VERSION,
    updated_at: new Date().toISOString(),
  };
}

export async function getUserAgreementRecord(
  supabase: SupabaseLikeClient,
  userId: string,
  fallbackMetadata?: Record<string, unknown> | undefined
) {
  const { data, error } = await (
    supabase.from("user_agreements") as {
      select: (columns: string) => {
        eq: (column: string, value: string) => {
          maybeSingle: () => PromiseLike<{ data: unknown; error: MessageError | null }>;
        };
      };
    }
  )
    .select("user_id, accepted_terms, accepted_at, ip_address, terms_version")
    .eq("user_id", userId)
    .maybeSingle();

  if (!error) {
    return {
      data: (data as UserAgreementRecord | null) ?? null,
      error: null,
    };
  }

  if (!isMissingAgreementTableError(error)) {
    return {
      data: null,
      error,
    };
  }

  if (!supabase.auth?.admin) {
    const fallbackData = parseAgreementFromMetadata(userId, fallbackMetadata);
    return {
      data: fallbackData,
      error: null,
    };
  }

  const adminUserResult = await supabase.auth.admin.getUserById(userId);
  const fallbackData = parseAgreementFromMetadata(
    userId,
    adminUserResult.data.user?.user_metadata ?? undefined
  );

  return {
    data: fallbackData,
    error: adminUserResult.error ?? null,
  };
}

export async function acceptUserAgreement(params: {
  supabase: SupabaseLikeClient;
  userId: string;
  ipAddress?: string | null;
  termsVersion?: string;
}) {
  const payload = buildAgreementAcceptance(params);

  const agreementTable = params.supabase.from("user_agreements") as unknown as {
    insert: (
      values: Record<string, unknown>
    ) => PromiseLike<{ data?: unknown; error: { message?: string | null } | null }>;
    update: (values: Record<string, unknown>) => {
      eq: (
        column: string,
        value: string
      ) => PromiseLike<{ data?: unknown; error: { message?: string | null } | null }>;
    };
  };

  const insertResult = await agreementTable.insert(payload);

  if (!insertResult.error) {
    return insertResult;
  }

  const duplicateKey =
    (insertResult.error.message ?? "").toLowerCase().includes("duplicate key") ||
    (insertResult.error.message ?? "").toLowerCase().includes("already exists");

  const tableResult = duplicateKey
    ? await agreementTable
        .update({
          accepted_terms: true,
          accepted_at: payload.accepted_at,
          ip_address: payload.ip_address,
          terms_version: payload.terms_version,
          updated_at: payload.updated_at,
        })
        .eq("user_id", params.userId)
    : insertResult;

  if (!isMissingAgreementTableError(tableResult.error)) {
    return tableResult;
  }

  if (!params.supabase.auth?.admin) {
    return {
      data: null,
      error: {
        message:
          "Agreement storage is unavailable. Create the user_agreements table or configure the Supabase service role key.",
      },
    };
  }

  const adminUserResult = await params.supabase.auth.admin.getUserById(params.userId);

  if (adminUserResult.error || !adminUserResult.data.user) {
    return {
      data: null,
      error: adminUserResult.error,
    };
  }

  const userMetadata = {
    ...(adminUserResult.data.user.user_metadata ?? {}),
    accepted_terms: true,
    accepted_at: payload.accepted_at,
    accepted_terms_ip: payload.ip_address,
    terms_version: payload.terms_version,
  };

  const updateResult = await params.supabase.auth.admin.updateUserById(params.userId, {
    user_metadata: userMetadata,
  });

  return {
    data: updateResult.data,
    error: updateResult.error,
  };
}

export const AGREEMENT_SECTIONS = {
  termsOfService: {
    title: "Terms of Service, Licensing, and Platform Use",
    sections: [
      {
        heading: "License and No Resale",
        body:
          "By using Safety360Docs, you agree that all generated documents and platform outputs are licensed, not sold. You may use them only for internal business purposes. You may not resell, redistribute, sublicense, share documents outside your organization, or use platform outputs to create competing products.",
      },
      {
        heading: "No Professional Advice",
        body:
          "Safety360Docs does not provide legal, engineering, or safety consulting. Nothing generated by the platform should be relied upon as legal, engineering, or professional safety advice. You agree to consult qualified professionals before implementation.",
      },
      {
        heading: "Account Abuse and Termination",
        body:
          "We reserve the right to suspend or terminate any account that violates these terms, including unauthorized sharing, resale, misuse of generated documents, or attempts to undermine the platform or its licensing protections.",
      },
      {
        heading: "Indemnification",
        body:
          "You agree to indemnify, defend, and hold harmless Safety360Docs, its owners, operators, affiliates, employees, and contractors from any claims, damages, losses, liabilities, costs, or legal actions arising out of your use of the platform, your use of generated documents, or your failure to verify compliance and jobsite safety obligations.",
      },
    ],
  },
  liabilityWaiver: {
    title: "Liability Waiver and Assumption of Risk",
    sections: [
      {
        heading: "As-Is Platform and Outputs",
        body:
          "All documents, templates, forms, and generated outputs are provided on an as-is and as-available basis for informational purposes only. Safety360Docs makes no guarantees regarding accuracy, regulatory compliance, completeness, or safety effectiveness.",
      },
      {
        heading: "User Responsibility",
        body:
          "You assume full responsibility for jobsite safety, compliance with OSHA and all applicable laws, verification of document accuracy, and implementation of all procedures, controls, and protective measures referenced by the platform or generated documents.",
      },
      {
        heading: "Limitation of Liability",
        body:
          "Safety360Docs is not liable for injury, death, property damage, OSHA violations, regulatory actions, project delays, financial loss, or any other damages arising from use of the platform or generated documents. Use of the platform is entirely at your own risk.",
      },
    ],
  },
} as const;

export function getDefaultAgreementConfig(): AgreementConfig {
  return {
    version: TERMS_VERSION,
    termsOfService: {
      title: AGREEMENT_SECTIONS.termsOfService.title,
      sections: AGREEMENT_SECTIONS.termsOfService.sections.map((section) => ({
        heading: section.heading,
        body: section.body,
      })),
    },
    liabilityWaiver: {
      title: AGREEMENT_SECTIONS.liabilityWaiver.title,
      sections: AGREEMENT_SECTIONS.liabilityWaiver.sections.map((section) => ({
        heading: section.heading,
        body: section.body,
      })),
    },
  };
}
