import { describe, expect, it } from "vitest";
import {
  cleanFinalText,
  cleanSectionForFinalIssue,
  normalizeFinalExportText,
} from "@/lib/csepFinalization";

describe("csepFinalization", () => {
  it("removes platform generator drafting phrases from final text", () => {
    expect(
      cleanFinalText(
        "This section was seeded from the platform generator during draft assembly."
      )
    ).toBeNull();

    expect(
      cleanFinalText(
        "Generated by the platform generator for builder review only. Emergency crews shall report to the main gate."
      )
    ).toBe("Emergency crews shall report to the main gate.");

    expect(
      cleanFinalText(
        "Platform generator note: Seeded content from the platform generator should be replaced before issue. Maintain fire extinguisher access."
      )
    ).toBe("Maintain fire extinguisher access.");
  });

  it("preserves legitimate field references that use the word generator", () => {
    expect(
      cleanFinalText("Portable generator cords shall be inspected before each shift.")
    ).toBe("Portable generator cords shall be inspected before each shift.");
  });

  it("drops the controlled placeholder unless explicitly allowed", () => {
    expect(cleanFinalText("TBD by contractor before issue")).toBeNull();
    expect(cleanFinalText("TBD by contractor before issue", { allowTbd: true })).toBe(
      "TBD by contractor before issue"
    );
  });

  it("converts unresolved table placeholders to N/A during final issue cleanup", () => {
    const cleaned = cleanSectionForFinalIssue({
      key: "policy_statement",
      title: "Contractor Safety Policy Statement",
      table: {
        columns: ["Requirement", "Details", "Responsible Party"],
        rows: [["Policy communication", "Discuss during orientation", "TBD by contractor before issue"]],
      },
    });

    expect(cleaned?.table?.rows).toEqual([["Policy communication", "Discuss during orientation", "N/A"]]);
  });

  it("normalizes internal automation labels into export-ready wording", () => {
    expect(
      normalizeFinalExportText(
        "Applicability / trigger logic: Apply this module whenever Beam setting, Bolting is in the work plan."
      )
    ).toBe("This section applies when Beam setting, Bolting is in the work plan.");

    expect(
      normalizeFinalExportText(
        "Trigger / reference: Included for this scope based on the selected program hazard / fall protection. Review these sections first: module scope and main exposures."
      )
    ).toBe(
      "This section is included because the selected work involves the fall protection. Related considerations include module scope and main exposures."
    );

    expect(
      normalizeFinalExportText(
        "Interfaces to coordinate: deck crews and crane crew. Use this module to align sequence, access, and handoffs with that work."
      )
    ).toBe("Coordinate with deck crews and crane crew.");
  });

  it("removes flattened related-considerations leaks, inline refs, and repeated wording", () => {
    expect(
      normalizeFinalExportText(
        "Related considerations include 1.1 Purpose Verify access. 1.2 Main hazards Watch overhead work."
      )
    ).toBeNull();

    expect(
      normalizeFinalExportText(
        "Workers should understand workers should understand the lift path (R1, R2, R3, R4)."
      )
    ).toBe("workers should understand the lift path.");
  });

  it("normalizes internal headings during final issue cleanup", () => {
    const cleaned = cleanSectionForFinalIssue({
      key: "program_module",
      title: "Program Purpose and Applicability",
      subsections: [
        {
          title: "Task Scope & Work Conditions",
          body: "Main exposure profile",
          bullets: ["Primary exposure", "Secondary exposure", "Changing condition risk"],
        },
      ],
    });

    expect(cleaned?.title).toBe("Purpose");
    expect(cleaned?.subsections?.[0]?.title).toBe("Task scope and work conditions");
    expect(cleaned?.subsections?.[0]?.body).toBe("Main hazards");
    expect(cleaned?.subsections?.[0]?.bullets).toEqual([
      "Primary hazard",
      "Additional hazard",
      "Changing site conditions",
    ]);
  });

  it("drops empty label-only subsection headings during final issue cleanup", () => {
    const cleaned = cleanSectionForFinalIssue({
      key: "task_module",
      title: "Task Modules",
      subsections: [
        {
          title: "Pre-task review",
          bullets: [],
        },
        {
          title: "Verification",
          body: "Document the pre-task brief and permit status.",
          bullets: [],
        },
      ],
    });

    expect(cleaned?.subsections).toEqual([
      {
        title: "Verification",
        body: "Document the pre-task brief and permit status.",
        bullets: [],
      },
    ]);
  });

  it("removes raw export label lines and humanizes raw source tokens", () => {
    expect(normalizeFinalExportText("Trade / Subtrade: Steel Erection / Decking")).toBeNull();
    expect(normalizeFinalExportText("Activity: Deck placement")).toBeNull();
    expect(
      normalizeFinalExportText(
        "Controls include fire_watch, spark_containment, flammable_clearance, signal_person, drop_zone_control, and lift_plan_review."
      )
    ).toBe(
      "Controls include fire watch, spark containment, flammable-material clearance, designated signal person, drop-zone control, and lift plan review."
    );
  });

  it("drops orphan builder filler sentences during final issue cleanup", () => {
    expect(
      normalizeFinalExportText(
        "This program establishes controls for elevated work and fall exposures."
      )
    ).toBeNull();
  });
});
