import type { GeneratedSafetyPlanSection } from "@/types/safety-intelligence";

const CONTROLLED_TBD = "TBD by contractor before issue";

const INTERNAL_PHRASE_PATTERNS = [
  /keep this section concise, customer-facing[^.]*\.?/gi,
  /use the front matter to orient field teams quickly[^.]*\.?/gi,
  /project-specific content will be completed with ai drafting and builder inputs where the platform has supporting data\.?/gi,
  /project-specific content will be completed during final contractor review\.?/gi,
  /the format package identified content that should stay visible in this section based on the current builder inputs\.?/gi,
  /ai final decision:\s*/gi,
  /platform-defined rule text/gi,
  /this section was seeded from the platform generator[^.]*\.?/gi,
  /seed(?:ed|ing)? (?:content|text|notes?|fields?|data) from the platform generator[^.]*\.?/gi,
  /generated by the platform generator[^.]*\.?/gi,
  /platform generator note:\s*/gi,
  /matched hazard modules attached[^.]*\.?/gi,
  /matched steel-erection hazard modules attached[^.]*\.?/gi,
  /raw reference notes?:?[^.]*\.?/gi,
  /document type:\s*[^|.\n]+(?:\s*\|\s*prepared:\s*[^|.\n]+)?(?:\s*\|\s*target length:\s*[^.\n]+)?\.?/gi,
  /\b(?:hazard|task) element\b/gi,
  /reference (?:steel-erection )?(?:task|hazard|program) modules? supporting the active scope\.?/gi,
  /reference (?:task|hazard) modules? supporting the selected (?:scope|hazards and permits)\.?/gi,
];

const EXPORT_TEXT_REMOVALS = [
  /Use this module to align sequence, access, and handoffs with that work\.?/gi,
  /selected program hazard\s*\/\s*/gi,
  /\((?:R\d+(?:,\s*)?)+\)/gi,
  /Related considerations include[^.]*\d+\.\d+[^.]*\.?/gi,
  /^\d+\.\d+\s+(?:Purpose|Main hazards?)[^.]*\.?/gi,
  /This program establishes controls[^.]*\.?/gi,
  /^\s*Field:\s*.+?\s+Value:\s*.+$/gim,
  /Project\s+.+?\s+is the active contractor planning record for this scope\.?/gi,
  /.+?\s+is the submitting contractor for this CSEP\.?/gi,
  /N\/A\s*\|\s*Contractor Logo\s*\/\s*Letterhead/gi,
  /\btest at test\b/gi,
  /Primary coordination contact:\s*test(?:,\s*test)+\.?/gi,
  /continuous improvement not only enhances safety outcomes[^.]*\.?/gi,
  /^\d+\.\d+\.\d+\s+required training\b[^.]*\.?/gim,
  /Required controls include Hole-cover trigger\.?/gi,
  /The following permit requirements were selected or derived[^.]*\.?/gi,
  /The following OSHA references? (?:were|was) (?:identified|selected)[^.]*\.?/gi,
  /The following hazards? (?:were|was) (?:selected|identified|derived)[^.]*\.?/gi,
  /The following overlapping trades? or affected scopes?[^.]*\.?/gi,
  /The following PPE (?:was|were) (?:selected|identified|derived)[^.]*\.?/gi,
  /The following controls? (?:were|was) (?:selected|identified|derived)[^.]*\.?/gi,
  /The following related tasks? (?:were|was) (?:selected|identified|derived)[^.]*\.?/gi,
  /The following (?:program|module|reference) (?:were|was) (?:selected|identified|derived)[^.]*\.?/gi,
  /[^.]*\bis the work site covered by this CSEP\.?/gi,
  /[^.]*\bis responsible for performing the work covered by this CSEP[^.]*\.?/gi,
  /This section identifies the project,\s*location,\s*and governing-site information used for field coordination\.?/gi,
  /(?:Project identification|Contractor contact) details were not fully provided in the current builder payload\.?/gi,
  // Remove only the capitalized placeholder name "Test" as a contractor /
  // subject placeholder (typical of dev seed data), not the lowercase noun
  // "test" which may legitimately appear in user-supplied content.
  /(?:^|\.\s+|\n)\s*Test\s+is\s+responsible for[^.]*\.?/g,
];

const EXPORT_TEXT_REPLACEMENTS: Array<[RegExp, string]> = [
  [/^Trigger \/ reference:\s*/gi, ""],
  [/^Applicability \/ trigger logic:\s*Apply this module whenever\s*/gi, "This section applies when "],
  [/^Applicability \/ trigger logic:\s*Apply this program before\s*/gi, "This section applies before "],
  [/^Applicability \/ trigger logic:\s*/gi, "This section applies when "],
  [
    /Included for this scope based on/gi,
    "This section is included because the selected work involves",
  ],
  [/Review these sections first:/gi, "Related considerations include"],
  [/Interfaces to coordinate:/gi, "Coordinate with"],
  [/\bPrimary exposure\b/gi, "Primary hazard"],
  [/\bSecondary exposure\b/gi, "Additional hazard"],
  [/\bChanging condition risk\b/gi, "Changing site conditions"],
  [/\bTask Scope\s*&\s*Work Conditions\b/gi, "Task scope and work conditions"],
  [/\bTask purpose\b/gi, "Purpose"],
  [/\bMain exposure profile\b/gi, "Main hazards"],
  [/\bProgram Purpose and Applicability\b/gi, "Purpose"],
  [/\bRoles and Responsibilities\b/gi, "Responsibilities"],
];

const INVALID_EXACT_TOKENS = new Set([
  "test",
  "pending approval",
  "null",
  "undefined",
  "[platform fill field]",
  "[fill]",
  "platform generator",
  "safetydocs360 ai draft builder",
  "safetydocs360 draft builder",
]);

const PERMIT_DEFINITIONS = [
  { id: "hot_work_permit", label: "Hot Work Permit", aliases: ["hot work", "hot work permit"] },
  {
    id: "elevated_work_notice",
    label: "Elevated Work Notice",
    aliases: ["elevated work notice", "ladder permit", "ladder permits", "elevated work", "work at height notice"],
  },
  {
    id: "lift_plan",
    label: "Lift Plan",
    aliases: ["lift plan", "critical lift plan", "crane lift plan"],
  },
  {
    id: "pick_plan",
    label: "Pick Plan",
    aliases: ["pick plan", "crane pick plan", "steel pick plan"],
  },
  {
    id: "crane_permit",
    label: "Crane Permit",
    aliases: ["crane permit", "crane use permit", "crane operation permit", "crane setup permit"],
  },
  {
    id: "awp_mewp_permit",
    label: "AWP/MEWP Permit",
    aliases: [
      "awp permit",
      "mewp permit",
      "awp mewp permit",
      "awp/mewp permit",
      "aerial lift permit",
      "aerial work platform permit",
    ],
  },
  {
    id: "gravity_permit",
    label: "Gravity Permit",
    aliases: ["gravity permit", "overhead work permit", "overhead hazard permit", "drop zone permit"],
  },
  {
    id: "motion_permit",
    label: "Motion Permit",
    aliases: ["motion permit", "equipment motion permit", "traffic control permit"],
  },
  {
    id: "energized_electrical_permit",
    label: "Energized Electrical Permit",
    aliases: ["energized electrical permit", "electrical permit", "energized work permit"],
  },
  {
    id: "excavation_permit",
    label: "Ground Disturbance Permit",
    aliases: ["excavation permit", "ground disturbance permit", "groundbreaking/excavation"],
  },
  {
    id: "confined_space_permit",
    label: "Confined Space Permit",
    aliases: ["confined space permit", "confined space entry permit"],
  },
] as const;

const HAZARD_ALIASES: Record<string, string> = {
  "fall": "Fall Exposure",
  "falls": "Fall Exposure",
  "falls from height": "Fall Exposure",
  "fall exposure": "Fall Exposure",
  "fire": "Fire",
  "hot work": "Hot Work",
  "struck by": "Struck-By",
  "struck by equipment": "Struck-By",
  "line of fire": "Line of Fire",
  "falling object hazards": "Falling Objects",
  "falling objects": "Falling Objects",
  "rigging and lifting hazards": "Rigging and Lifting Hazards",
  "crane lift hazards": "Crane Lift Hazards",
};

const PPE_ALIASES: Record<string, string> = {
  "hard hat": "Hard Hat",
  "safety glasses": "Safety Glasses",
  "gloves": "Gloves",
  "high visibility vest": "High-Visibility Vest",
  "high visibility vests": "High-Visibility Vest",
  "hi vis vest": "High-Visibility Vest",
  "steel toe boots": "Steel-Toe Boots",
  "fall protection harness": "Fall Protection Harness",
  "harness": "Fall Protection Harness",
  "hearing protection": "Hearing Protection",
};

const INTERFACE_TRADE_TOKENS = [
  "fire protection",
  "hvac",
  "mechanical",
  "painting",
  "coatings",
  "electrical rough-in",
  "plumbing",
  "sprinkler",
];

const RAW_SOURCE_TOKEN_ALIASES: Record<string, string> = {
  fire_watch: "fire watch",
  spark_containment: "spark containment",
  sparks_contained: "spark containment",
  flammable_clearance: "flammable-material clearance",
  signal_person: "designated signal person",
  drop_zone_control: "drop-zone control",
  lift_plan_review: "lift plan review",
};

function normalizeToken(value: string | null | undefined) {
  return (value ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function collapseRepeatedPhrases(value: string) {
  return value
    .replace(/\b([a-z]+)\s+\1\b/gi, "$1")
    .replace(/\b((?:[a-z]+(?:\s+[a-z]+){1,4}))\s+\1\b/gi, "$1");
}

function stripInlineReferenceTags(value: string) {
  return value.replace(/\s*\((?:R\d+(?:,\s*)?)+\)\s*/gi, " ");
}

function humanizeRawSourceToken(value: string) {
  const trimmed = value.trim();
  if (!/^[a-z0-9]+(?:_[a-z0-9]+)+$/.test(trimmed)) {
    return trimmed;
  }

  return RAW_SOURCE_TOKEN_ALIASES[trimmed] ?? trimmed.replace(/_/g, " ");
}

function normalizeRawSourceTokens(value: string) {
  return value.replace(/\b[a-z0-9]+(?:_[a-z0-9]+)+\b/g, (token) => humanizeRawSourceToken(token));
}

export function cleanFinalText(value: string | null | undefined, options?: { allowTbd?: boolean }) {
  if (!value?.trim()) return null;

  let cleaned = value.trim();
  for (const pattern of INTERNAL_PHRASE_PATTERNS) {
    cleaned = cleaned.replace(pattern, " ");
  }

  cleaned = cleaned
    .replace(/\[(platform fill field|fill)\]/gi, " ")
    .replace(/\s+/g, " ")
    .trim();

  if (!cleaned) return options?.allowTbd ? CONTROLLED_TBD : null;

  if (INVALID_EXACT_TOKENS.has(cleaned.toLowerCase())) {
    return options?.allowTbd ? CONTROLLED_TBD : null;
  }

  if (cleaned.toLowerCase() === CONTROLLED_TBD.toLowerCase()) {
    return options?.allowTbd ? CONTROLLED_TBD : null;
  }

  return cleaned;
}

export function normalizeFinalExportText(
  value: string | null | undefined,
  options?: { allowTbd?: boolean }
) {
  const cleaned = cleanFinalText(value, options);
  if (!cleaned) return cleaned;

  if (
    /^(?:Trade\s*\/\s*Subtrade|Activity|Hazards?|Controls?|PPE|Permits?|Competency)\s*:/i.test(
      cleaned
    )
  ) {
    return null;
  }

  let normalized = cleaned;
  for (const pattern of EXPORT_TEXT_REMOVALS) {
    normalized = normalized.replace(pattern, " ");
  }

  normalized = stripInlineReferenceTags(normalized);
  normalized = normalizeRawSourceTokens(normalized);

  for (const [pattern, replacement] of EXPORT_TEXT_REPLACEMENTS) {
    normalized = normalized.replace(pattern, replacement);
  }

  normalized = normalized
    .replace(/^\s*\d+\.\d+\s+(?:Purpose|Main hazards?).*$/i, " ")
    .replace(/\bworkers should understand workers should understand\b/gi, "workers should understand")
    .replace(/\bworkers shall be trained on workers shall be trained on\b/gi, "workers shall be trained on")
    .replace(/\bcontinuous improvement\b.*?\bcontinuous improvement\b/gi, "continuous improvement")
    .replace(/\brecordkeeping\b.*?\brecordkeeping\b/gi, "recordkeeping")
    .replace(/\btraining\b.*?\btraining\b/gi, "training")
    .replace(/\s*\((?:\s*,?\s*)*\)\s*/g, " ")
    .replace(/\s+-\s*$/g, "")
    .replace(/:\s*$/g, "")
    .replace(/;\s*$/g, "")
    .replace(/\s{2,}/g, " ")
    .replace(/\s+([,.;:])/g, "$1")
    .replace(/\s{2,}/g, " ")
    .trim();

  normalized = collapseRepeatedPhrases(normalized);

  return normalized || (options?.allowTbd ? CONTROLLED_TBD : null);
}

export function isMeaningfulFinalText(value: string | null | undefined) {
  const cleaned = cleanFinalText(value);
  return Boolean(cleaned && cleaned !== CONTROLLED_TBD);
}

function normalizeDisplayList(
  values: Array<string | null | undefined>,
  aliasMap: Record<string, string>
) {
  const out: string[] = [];
  const seen = new Set<string>();

  for (const raw of values) {
    const cleaned = cleanFinalText(raw);
    if (!cleaned) continue;
    const normalized = normalizeToken(cleaned);
    const display = aliasMap[normalized] ?? cleaned;
    const key = normalizeToken(display);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(display);
  }

  return out;
}

export function normalizeHazardList(values: Array<string | null | undefined>) {
  return normalizeDisplayList(values, HAZARD_ALIASES);
}

export function normalizePpeList(values: Array<string | null | undefined>) {
  return normalizeDisplayList(values, PPE_ALIASES);
}

export function normalizePermitList(values: Array<string | null | undefined>) {
  const out: string[] = [];
  const seen = new Set<string>();

  for (const raw of values) {
    const cleaned = cleanFinalText(raw);
    if (!cleaned) continue;
    const normalized = normalizeToken(cleaned);
    const permit =
      PERMIT_DEFINITIONS.find((item) => item.id === normalized) ??
      PERMIT_DEFINITIONS.find((item) =>
        item.aliases.some((alias) => normalizeToken(alias) === normalized)
      );
    const display = permit?.label ?? cleaned;
    const key = normalizeToken(display);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(display);
  }

  return out;
}

export function normalizeTaskList(values: Array<string | null | undefined>) {
  const out: string[] = [];
  const seen = new Set<string>();

  for (const raw of values) {
    const cleaned = cleanFinalText(raw);
    if (!cleaned) continue;
    const key = normalizeToken(cleaned);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(cleaned);
  }

  return out;
}

export function splitScopeTasksAndInterfaces(values: Array<string | null | undefined>) {
  const activeTasks: string[] = [];
  const interfaceTrades: string[] = [];
  const seenActive = new Set<string>();
  const seenInterface = new Set<string>();

  for (const raw of values) {
    const cleaned = cleanFinalText(raw);
    if (!cleaned) continue;
    const normalized = normalizeToken(cleaned);
    const isInterface = INTERFACE_TRADE_TOKENS.some((token) => normalized.includes(token));

    if (isInterface) {
      if (!seenInterface.has(normalized)) {
        seenInterface.add(normalized);
        interfaceTrades.push(cleaned);
      }
      continue;
    }

    if (!seenActive.has(normalized)) {
      seenActive.add(normalized);
      activeTasks.push(cleaned);
    }
  }

  return { activeTasks, interfaceTrades };
}

export function cleanSectionForFinalIssue(
  section: GeneratedSafetyPlanSection
): GeneratedSafetyPlanSection | null {
  const title = normalizeFinalExportText(section.title);
  if (!title) return null;

  const summary = normalizeFinalExportText(section.summary);
  const body = normalizeFinalExportText(section.body);
  const bullets = (section.bullets ?? [])
    .map((item) => normalizeFinalExportText(item))
    .filter((item): item is string => Boolean(item));
  const subsections = (section.subsections ?? [])
    .map((subsection) => {
      const subsectionTitle = normalizeFinalExportText(subsection.title);
      const subsectionBody = normalizeFinalExportText(subsection.body);
      const subsectionBullets = subsection.bullets
        .map((item) => normalizeFinalExportText(item))
        .filter((item): item is string => Boolean(item));

      const normalizedTitle = normalizeToken(subsectionTitle);
      const filteredBullets = subsectionBullets.filter((item, index, items) => {
        const normalizedItem = normalizeToken(item);
        if (!normalizedItem) return false;
        if (normalizedTitle && normalizedItem === normalizedTitle) return false;
        return items.findIndex((candidate) => normalizeToken(candidate) === normalizedItem) === index;
      });

      const labelOnlyHeading =
        Boolean(normalizedTitle) &&
        !subsectionBody &&
        filteredBullets.length === 0;

      if ((!subsectionTitle && !subsectionBody && !filteredBullets.length) || labelOnlyHeading) {
        return null;
      }

      const cleanedSubsection: NonNullable<GeneratedSafetyPlanSection["subsections"]>[number] = {
        title: subsectionTitle ?? "Details",
        bullets: filteredBullets,
      };

      if (subsectionBody) {
        cleanedSubsection.body = subsectionBody;
      }

      return cleanedSubsection;
    })
    .filter(
      (
        subsection
      ): subsection is NonNullable<GeneratedSafetyPlanSection["subsections"]>[number] =>
        Boolean(subsection)
    );
  const table = section.table
    ? {
        columns: section.table.columns
          .map((column) => normalizeFinalExportText(column))
          .filter((column): column is string => Boolean(column)),
        rows: section.table.rows
          .map((row) =>
            row
              .map((cell) => normalizeFinalExportText(cell) ?? "N/A")
              .filter((cell): cell is string => Boolean(cell))
          )
          .filter((row) => row.length > 0),
      }
    : null;

  if (!summary && !body && bullets.length === 0 && subsections.length === 0 && !table?.rows.length) {
    return null;
  }

  return {
    ...section,
    title,
    summary: summary ?? undefined,
    body: body ?? undefined,
    bullets: bullets.length ? bullets : undefined,
    subsections: subsections.length ? subsections : undefined,
    table:
      table && table.columns.length && table.rows.length
        ? table
        : null,
  };
}

export function controlledTbd() {
  return CONTROLLED_TBD;
}
