import type { GeneratedSafetyPlanSection } from "@/types/safety-intelligence";

const CONTROLLED_TBD = "TBD by contractor before issue";

const INTERNAL_PHRASE_PATTERNS = [
  /keep this section concise, customer-facing[^.]*\.?/gi,
  /use the front matter to orient field teams quickly[^.]*\.?/gi,
  /project-specific content will be completed with ai drafting and builder inputs where the platform has supporting data\.?/gi,
  /project-specific content will be completed during final contractor review\.?/gi,
  /builder lines beginning with[^.]*environmental control[^.]*\.?/gi,
  /this section was seeded from the platform generator[^.]*\.?/gi,
  /seed(?:ed|ing)? (?:content|text|notes?|fields?|data) from the platform generator[^.]*\.?/gi,
  /generated by the platform generator[^.]*\.?/gi,
  /platform generator note:\s*/gi,
  /\bAI[-\s]?generated\b/gi,
  /\bautomation (?:pipeline|rules?|engine)\b/gi,
  /\bfallback (?:copy|text|narrative|content)\b/gi,
  /\bseeded (?:from|content|text)\b/gi,
  /ai final decision:\s*/gi,
  /platform-defined rule text/gi,
  /matched hazard modules attached[^.]*\.?/gi,
  /matched steel-erection hazard modules attached[^.]*\.?/gi,
  /raw reference notes?:?[^.]*\.?/gi,
  /document type:\s*[^|.\n]+(?:\s*\|\s*prepared:\s*[^|.\n]+)?(?:\s*\|\s*target length:\s*[^.\n]+)?\.?/gi,
  /\b(?:hazard|task) element\b/gi,
  /reference (?:steel-erection )?(?:task|hazard|program) modules? supporting the active scope\.?/gi,
  /reference (?:task|hazard) modules? supporting the selected (?:scope|hazards and permits)\.?/gi,
];

const EXPORT_TEXT_REMOVALS = [
  /Use this module to align sequence, access, and handoffs with that work\.?/gi,
  /selected program hazard\s*\/\s*/gi,
  /\((?:R\d+(?:,\s*)?)+\)/gi,
  /Related considerations include[^.]*\d+\.\d+[^.]*\.?/gi,
  /^\d+\.\d+\s+(?:Purpose|Main hazards?)[^.]*\.?/gi,
  /This program establishes controls[^.]*\.?/gi,
  /^\s*Field:\s*.+?\s+Value:\s*.+$/gim,
  /Project\s+.+?\s+is the active contractor planning record for this scope\.?/gi,
  /.+?\s+is the submitting contractor for this CSEP\.?/gi,
  /N\/A\s*\|\s*Contractor Logo\s*\/\s*Letterhead/gi,
  /\btest at test\b/gi,
  /Primary coordination contact:\s*test(?:,\s*test)+\.?/gi,
  /continuous improvement not only enhances safety outcomes[^.]*\.?/gi,
  /^\d+\.\d+\.\d+\s+required training\b[^.]*\.?/gim,
  /Required controls include Hole-cover trigger\.?/gi,
  /The following permit requirements were selected or derived[^.]*\.?/gi,
  /The following OSHA references? (?:were|was) (?:identified|selected)[^.]*\.?/gi,
  /The following hazards? (?:were|was) (?:selected|identified|derived)[^.]*\.?/gi,
  /The following overlapping trades? or affected scopes?[^.]*\.?/gi,
  /The following PPE (?:was|were) (?:selected|identified|derived)[^.]*\.?/gi,
  /The following controls? (?:were|was) (?:selected|identified|derived)[^.]*\.?/gi,
  /The following related tasks? (?:were|was) (?:selected|identified|derived)[^.]*\.?/gi,
  /The following (?:program|module|reference) (?:were|was) (?:selected|identified|derived)[^.]*\.?/gi,
  /[^.]*\bis the work site covered by this CSEP\.?/gi,
  /[^.]*\bis responsible for performing the work covered by this CSEP[^.]*\.?/gi,
  /This section identifies the project,\s*location,\s*and governing-site information used for field coordination\.?/gi,
  // Remove only the capitalized placeholder name "Test" as a contractor /
  // subject placeholder (typical of dev seed data), not the lowercase noun
  // "test" which may legitimately appear in user-supplied content.
  /(?:^|\.\s+|\n)\s*Test\s+is\s+responsible for[^.]*\.?/g,
];

const EXPORT_TEXT_REPLACEMENTS: Array<[RegExp, string]> = [
  [/^Minimum Requirements?:\s*/gim, ""],
  [/^Minimum Cadence:\s*/gim, "Requirement: "],
  [/^Minimum Frequency:\s*/gim, "Requirement: "],
  [/\bMinimum Cadence\b/gi, "Requirement"],
  [/\bMinimum Frequency\b/gi, "Requirement"],
  [/^Trigger \/ reference:\s*/gi, ""],
  [/^Applicability \/ trigger logic:\s*Apply this module whenever\s*/gi, "This section applies when "],
  [/^Applicability \/ trigger logic:\s*Apply this program before\s*/gi, "This section applies before "],
  [/^Applicability \/ trigger logic:\s*/gi, "This section applies when "],
  [
    /Included for this scope based on/gi,
    "This section is included because the selected work involves",
  ],
  [/Review these sections first:/gi, "Related considerations include"],
  [/Interfaces to coordinate:/gi, "Coordinate with"],
  [/\bPrimary exposure\b/gi, "Primary hazard"],
  [/\bSecondary exposure\b/gi, "Additional hazard"],
  [/\bChanging condition risk\b/gi, "Changing site conditions"],
  [/\bTask Scope\s*&\s*Work Conditions\b/gi, "Task scope and work conditions"],
  [/\bTask purpose\b/gi, "Purpose"],
  [/\bMain exposure profile\b/gi, "Main hazards"],
  [/\bProgram Purpose and Applicability\b/gi, "Purpose"],
  [/\bRoles and Responsibilities\b/gi, "Responsibilities"],
  [/\bCross-read\b/gi, "See"],
  [/\bline-listed\b/gi, "listed"],
  [/\bthe generated plan\b/gi, "this plan"],
  [/\bgenerated plan\b/gi, "plan"],
  [/\bContractor narrative \(from builder\):\s*/gi, "Contractor scope narrative: "],
  [/\bProject-specific health notes \(from builder\):\s*/gi, "Project-specific health notes: "],
  [/\bBuilder or project-specific requirements:\s*/gi, "Project-specific requirements: "],
  [/\bas the site names them\b/gi, "as listed on the project permit register"],
  [
    /The format package identified content that should stay visible in this section based on the current builder inputs\.?/gi,
    "Confirm subsection coverage against the information entered for this CSEP before issue.",
  ],
  [
    /(?:Project identification|Contractor contact) details were not fully provided in the current builder payload\.?/gi,
    "Complete project identification and contractor contact information before issue.",
  ],
  [
    /Scope summary details were not entered in the current builder payload\.?/gi,
    "Add the contractor scope narrative for this trade package in Section 3 before issue.",
  ],
  [
    /Emergency procedures were not entered in the current builder payload\.?/gi,
    "Complete emergency response procedures in Section 10 before issue.",
  ],
];

const INVALID_EXACT_TOKENS = new Set([
  "test",
  "pending approval",
  "null",
  "undefined",
  "[platform fill field]",
  "[fill]",
  "platform generator",
  "safetydocs360 ai draft builder",
  "safetydocs360 draft builder",
]);

const PERMIT_DEFINITIONS = [
  { id: "hot_work_permit", label: "Hot Work Permit", aliases: ["hot work", "hot work permit"] },
  {
    id: "elevated_work_notice",
    label: "Elevated Work Notice",
    aliases: ["elevated work notice", "ladder permit", "ladder permits", "elevated work", "work at height notice"],
  },
  {
    id: "lift_plan",
    label: "Lift Plan",
    aliases: ["lift plan", "critical lift plan", "crane lift plan"],
  },
  {
    id: "pick_plan",
    label: "Pick Plan",
    aliases: ["pick plan", "crane pick plan", "steel pick plan"],
  },
  {
    id: "crane_permit",
    label: "Crane Permit",
    aliases: ["crane permit", "crane use permit", "crane operation permit", "crane setup permit"],
  },
  {
    id: "awp_mewp_permit",
    label: "AWP/MEWP Permit",
    aliases: [
      "awp permit",
      "mewp permit",
      "awp mewp permit",
      "awp/mewp permit",
      "aerial lift permit",
      "aerial work platform permit",
    ],
  },
  {
    id: "gravity_permit",
    label: "Gravity Permit",
    aliases: ["gravity permit", "overhead work permit", "overhead hazard permit", "drop zone permit"],
  },
  {
    id: "motion_permit",
    label: "Motion Permit",
    aliases: ["motion permit", "equipment motion permit", "traffic control permit"],
  },
  {
    id: "energized_electrical_permit",
    label: "Energized Electrical Permit",
    aliases: ["energized electrical permit", "electrical permit", "energized work permit"],
  },
  {
    id: "excavation_permit",
    label: "Ground Disturbance Permit",
    aliases: ["excavation permit", "ground disturbance permit", "groundbreaking/excavation"],
  },
  {
    id: "confined_space_permit",
    label: "Confined Space Permit",
    aliases: ["confined space permit", "confined space entry permit"],
  },
] as const;

const HAZARD_ALIASES: Record<string, string> = {
  "fall": "Fall Exposure",
  "falls": "Fall Exposure",
  "falls from height": "Fall Exposure",
  "fall exposure": "Fall Exposure",
  "fire": "Fire",
  "hot work": "Hot Work",
  "struck by": "Struck-By",
  "struck by equipment": "Struck-By",
  "line of fire": "Line of Fire",
  "falling object hazards": "Falling Objects",
  "falling objects": "Falling Objects",
  "rigging and lifting hazards": "Rigging and Lifting Hazards",
  "crane lift hazards": "Crane Lift Hazards",
};

const PPE_ALIASES: Record<string, string> = {
  "hard hat": "Hard Hat",
  "safety glasses": "Safety glasses",
  "safety glass": "Safety glasses",
  "eye protection": "Safety glasses",
  "gloves": "Gloves",
  "high visibility vest": "High-visibility vest or shirt",
  "high visibility vests": "High-visibility vest or shirt",
  "hi vis vest": "High-visibility vest or shirt",
  "high visibility vest or shirt": "High-visibility vest or shirt",
  "steel toe boots": "Safety-toe boots",
  "steel-toe boots": "Safety-toe boots",
  "safety toe boots": "Safety-toe boots",
  "protective footwear": "Safety-toe boots",
  "work boots": "Safety-toe boots",
  "fall protection harness": "Fall protection harness",
  "harness": "Fall protection harness",
  "hearing protection": "Hearing protection",
  "fall protection": "Fall protection",
  "welding hood": "Welding hood",
  "welding gloves": "Welding gloves",
  "face shield": "Face shield",
  "respiratory protection": "Respiratory protection",
  "respirator": "Respiratory protection",
  "cut resistant gloves": "Cut-resistant gloves",
  "cut-resistant gloves": "Cut-resistant gloves",
  "fr clothing": "FR clothing",
  "chemical resistant gloves": "Chemical-resistant gloves",
  "chemical-resistant gloves": "Chemical-resistant gloves",
  "srl": "Lanyard / SRL",
  "self retracting lifeline": "Lanyard / SRL",
  "self-retracting lifeline": "Lanyard / SRL",
  "lanyard": "Lanyard / SRL",
  "awp fall protection": "AWP / MEWP fall protection",
  "mewp fall protection": "AWP / MEWP fall protection",
};

const INTERFACE_TRADE_TOKENS = [
  "fire protection",
  "hvac",
  "mechanical",
  "painting",
  "coatings",
  "electrical rough-in",
  "plumbing",
  "sprinkler",
];

const RAW_SOURCE_TOKEN_ALIASES: Record<string, string> = {
  fire_watch: "fire watch",
  spark_containment: "spark containment",
  sparks_contained: "spark containment",
  flammable_clearance: "flammable-material clearance",
  signal_person: "designated signal person",
  drop_zone_control: "drop-zone control",
  lift_plan_review: "lift plan review",
};

function normalizeToken(value: string | null | undefined) {
  return (value ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function collapseRepeatedPhrases(value: string) {
  return value
    .replace(/\b([a-z]+)\s+\1\b/gi, "$1")
    .replace(/\b((?:[a-z]+(?:\s+[a-z]+){1,4}))\s+\1\b/gi, "$1");
}

function stripInlineReferenceTags(value: string) {
  return value.replace(/\s*\((?:R\d+(?:,\s*)?)+\)\s*/gi, " ");
}

function humanizeRawSourceToken(value: string) {
  const trimmed = value.trim();
  if (!/^[a-z0-9]+(?:_[a-z0-9]+)+$/.test(trimmed)) {
    return trimmed;
  }

  return RAW_SOURCE_TOKEN_ALIASES[trimmed] ?? trimmed.replace(/_/g, " ");
}

function normalizeRawSourceTokens(value: string) {
  return value.replace(/\b[a-z0-9]+(?:_[a-z0-9]+)+\b/g, (token) => humanizeRawSourceToken(token));
}

export function cleanFinalText(value: string | null | undefined, options?: { allowTbd?: boolean }) {
  if (!value?.trim()) return null;

  let cleaned = value.trim();
  for (const pattern of INTERNAL_PHRASE_PATTERNS) {
    cleaned = cleaned.replace(pattern, " ");
  }

  cleaned = cleaned
    .replace(/\[(platform fill field|fill)\]/gi, " ")
    .replace(/\s+/g, " ")
    .trim();

  if (!cleaned) return options?.allowTbd ? CONTROLLED_TBD : null;

  if (INVALID_EXACT_TOKENS.has(cleaned.toLowerCase())) {
    return options?.allowTbd ? CONTROLLED_TBD : null;
  }

  if (cleaned.toLowerCase() === CONTROLLED_TBD.toLowerCase()) {
    return options?.allowTbd ? CONTROLLED_TBD : null;
  }

  return cleaned;
}

export function normalizeFinalExportText(
  value: string | null | undefined,
  options?: { allowTbd?: boolean }
) {
  const cleaned = cleanFinalText(value, options);
  if (!cleaned) return cleaned;

  if (
    /^(?:Trade\s*\/\s*Subtrade|Activity|Hazards?|Controls?|PPE|Permits?|Competency)\s*:/i.test(
      cleaned
    )
  ) {
    return null;
  }

  let normalized = cleaned;
  for (const pattern of EXPORT_TEXT_REMOVALS) {
    normalized = normalized.replace(pattern, " ");
  }

  normalized = stripInlineReferenceTags(normalized);
  normalized = normalizeRawSourceTokens(normalized);

  for (const [pattern, replacement] of EXPORT_TEXT_REPLACEMENTS) {
    normalized = normalized.replace(pattern, replacement);
  }

  normalized = normalized
    .replace(/^\s*\d+\.\d+\s+(?:Purpose|Main hazards?).*$/i, " ")
    .replace(/\bworkers should understand workers should understand\b/gi, "workers should understand")
    .replace(/\bworkers shall be trained on workers shall be trained on\b/gi, "workers shall be trained on")
    .replace(/\bcontinuous improvement\b.*?\bcontinuous improvement\b/gi, "continuous improvement")
    .replace(/\brecordkeeping\b.*?\brecordkeeping\b/gi, "recordkeeping")
    .replace(/\btraining\b.*?\btraining\b/gi, "training")
    .replace(/\s*\((?:\s*,?\s*)*\)\s*/g, " ")
    .replace(/\s+-\s*$/g, "")
    .replace(/:\s*$/g, "")
    .replace(/;\s*$/g, "")
    .replace(/\s{2,}/g, " ")
    .replace(/\s+([,.;:])/g, "$1")
    .replace(/\s{2,}/g, " ")
    .trim();

  normalized = collapseRepeatedPhrases(normalized);

  return normalized || (options?.allowTbd ? CONTROLLED_TBD : null);
}

export function isMeaningfulFinalText(value: string | null | undefined) {
  const cleaned = cleanFinalText(value);
  return Boolean(cleaned && cleaned !== CONTROLLED_TBD);
}

function normalizeDisplayList(
  values: Array<string | null | undefined>,
  aliasMap: Record<string, string>
) {
  const out: string[] = [];
  const seen = new Set<string>();

  for (const raw of values) {
    const cleaned = cleanFinalText(raw);
    if (!cleaned) continue;
    const normalized = normalizeToken(cleaned);
    const display = aliasMap[normalized] ?? cleaned;
    const key = normalizeToken(display);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(display);
  }

  return out;
}

export function normalizeHazardList(values: Array<string | null | undefined>) {
  return normalizeDisplayList(values, HAZARD_ALIASES);
}

export function normalizePpeList(values: Array<string | null | undefined>) {
  return normalizeDisplayList(values, PPE_ALIASES);
}

/** Fixed baseline PPE; task- or exposure-specific items are listed in the add-on line. */
export const CSEP_BASELINE_PPE_DISPLAY: readonly string[] = [
  "Hard Hat",
  "Safety glasses",
  "High-visibility vest or shirt",
  "Gloves",
  "Safety-toe boots",
] as const;

const BASELINE_PPE_NORMALIZED = new Set(
  CSEP_BASELINE_PPE_DISPLAY.map((label) => normalizeToken(label))
);

function isBaselinePpeDisplay(display: string): boolean {
  const t = normalizeToken(display);
  if (!BASELINE_PPE_NORMALIZED.has(t)) return false;
  if (t === "gloves" && /\b(cut|welding|chemical|heat|nitrile|latex|electrical|arc|insulated)\b/i.test(display)) {
    return false;
  }
  return true;
}

/**
 * Normalizes and deduplicates PPE labels for export (e.g. "Steel-Toe Boots" vs "safety-toe boots").
 * Drops generic "Fall protection" when a specific harness / lanyard / SRL-type item is present.
 */
export function dedupePpeItemsForExport(values: Array<string | null | undefined>): string[] {
  const list = normalizePpeList(values);
  const hasHarnessLike = list.some((item) => normalizeToken(item) === "fall protection harness");
  const hasSpecificFall = list.some((item) =>
    /\b(harness|lanyard|\bsrl\b|self[-\s]?retracting|personal fall arrest|lifeline|retractable lifeline)\b/i.test(
      item
    )
  );

  return list.filter((item) => {
    const t = normalizeToken(item);
    if (t === "fall protection" && (hasHarnessLike || hasSpecificFall)) return false;
    return true;
  });
}

const FALL_ADDON_WHEN_UNSPECIFIED =
  "Fall protection harness, lanyard, or SRL when the task, exposure, or site rules require them";

/** Parses structured PPE bullets (or legacy flat labels) back into raw item labels. */
export function flattenPpeSectionBulletsToItems(bullets: string[]): string[] {
  const out: string[] = [];
  for (const raw of bullets) {
    const b = raw.trim();
    if (!b) continue;
    const baselineMatch = /^Project baseline PPE:\s*(.+)$/i.exec(b);
    if (baselineMatch) {
      baselineMatch[1]
        .replace(/\.\s*$/, "")
        .split(";")
        .forEach((piece) => {
          const t = piece.trim();
          if (t) out.push(t);
        });
      continue;
    }
    const taskMatch = /^Task- and exposure-specific PPE:\s*(.+)$/i.exec(b);
    if (taskMatch) {
      taskMatch[1]
        .replace(/\.\s*$/, "")
        .split(";")
        .forEach((piece) => {
          const t = piece.trim();
          if (t) out.push(t);
        });
      continue;
    }
    out.push(b);
  }
  return out;
}

export function buildCsepPpeSectionBulletsFromCombined(combinedItems: string[]): string[] {
  const normalized = dedupePpeItemsForExport(combinedItems);
  const addons = normalized.filter((item) => !isBaselinePpeDisplay(item));
  const hasSpecificFall = addons.some((item) =>
    /\b(harness|lanyard|\bsrl\b|self[-\s]?retracting|personal fall arrest|lifeline)\b/i.test(item)
  );
  if (!hasSpecificFall) {
    addons.push(FALL_ADDON_WHEN_UNSPECIFIED);
  }

  const baselineText = `Project baseline PPE: ${CSEP_BASELINE_PPE_DISPLAY.join("; ")}.`;
  const addonText = `Task- and exposure-specific PPE: ${addons.join("; ")}.`;
  return [baselineText, addonText];
}

export function buildCsepPpeSectionBullets(ppeInput: string[], rulePpe: string[]): string[] {
  return buildCsepPpeSectionBulletsFromCombined([...ppeInput, ...rulePpe]);
}

export function normalizePermitList(values: Array<string | null | undefined>) {
  const out: string[] = [];
  const seen = new Set<string>();

  for (const raw of values) {
    const cleaned = cleanFinalText(raw);
    if (!cleaned) continue;
    const normalized = normalizeToken(cleaned);
    const permit =
      PERMIT_DEFINITIONS.find((item) => item.id === normalized) ??
      PERMIT_DEFINITIONS.find((item) =>
        item.aliases.some((alias) => normalizeToken(alias) === normalized)
      );
    const display = permit?.label ?? cleaned;
    const key = normalizeToken(display);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(display);
  }

  return out;
}

export function normalizeTaskList(values: Array<string | null | undefined>) {
  const out: string[] = [];
  const seen = new Set<string>();

  for (const raw of values) {
    const cleaned = cleanFinalText(raw);
    if (!cleaned) continue;
    const key = normalizeToken(cleaned);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(cleaned);
  }

  return out;
}

export function splitScopeTasksAndInterfaces(values: Array<string | null | undefined>) {
  const activeTasks: string[] = [];
  const interfaceTrades: string[] = [];
  const seenActive = new Set<string>();
  const seenInterface = new Set<string>();

  for (const raw of values) {
    const cleaned = cleanFinalText(raw);
    if (!cleaned) continue;
    const normalized = normalizeToken(cleaned);
    const isInterface = INTERFACE_TRADE_TOKENS.some((token) => normalized.includes(token));

    if (isInterface) {
      if (!seenInterface.has(normalized)) {
        seenInterface.add(normalized);
        interfaceTrades.push(cleaned);
      }
      continue;
    }

    if (!seenActive.has(normalized)) {
      seenActive.add(normalized);
      activeTasks.push(cleaned);
    }
  }

  return { activeTasks, interfaceTrades };
}

export function cleanSectionForFinalIssue(
  section: GeneratedSafetyPlanSection
): GeneratedSafetyPlanSection | null {
  const title = normalizeFinalExportText(section.title);
  if (!title) return null;

  const summary = normalizeFinalExportText(section.summary);
  const body = normalizeFinalExportText(section.body);
  const bullets = (section.bullets ?? [])
    .map((item) => normalizeFinalExportText(item))
    .filter((item): item is string => Boolean(item));
  const subsections = (section.subsections ?? [])
    .map((subsection) => {
      const subsectionTitle = normalizeFinalExportText(subsection.title);
      const subsectionBody = normalizeFinalExportText(subsection.body);
      const subsectionBullets = subsection.bullets
        .map((item) => normalizeFinalExportText(item))
        .filter((item): item is string => Boolean(item));

      const normalizedTitle = normalizeToken(subsectionTitle);
      const filteredBullets = subsectionBullets.filter((item, index, items) => {
        const normalizedItem = normalizeToken(item);
        if (!normalizedItem) return false;
        if (normalizedTitle && normalizedItem === normalizedTitle) return false;
        return items.findIndex((candidate) => normalizeToken(candidate) === normalizedItem) === index;
      });

      const labelOnlyHeading =
        Boolean(normalizedTitle) &&
        !subsectionBody &&
        filteredBullets.length === 0;

      if ((!subsectionTitle && !subsectionBody && !filteredBullets.length) || labelOnlyHeading) {
        return null;
      }

      const cleanedSubsection: NonNullable<GeneratedSafetyPlanSection["subsections"]>[number] = {
        title: subsectionTitle ?? "Details",
        bullets: filteredBullets,
      };

      if (subsectionBody) {
        cleanedSubsection.body = subsectionBody;
      }

      return cleanedSubsection;
    })
    .filter(
      (
        subsection
      ): subsection is NonNullable<GeneratedSafetyPlanSection["subsections"]>[number] =>
        Boolean(subsection)
    );
  const table = section.table
    ? {
        columns: section.table.columns
          .map((column) => normalizeFinalExportText(column))
          .filter((column): column is string => Boolean(column)),
        rows: section.table.rows
          .map((row) =>
            row
              .map((cell) => normalizeFinalExportText(cell) ?? "N/A")
              .filter((cell): cell is string => Boolean(cell))
          )
          .filter((row) => row.length > 0),
      }
    : null;

  if (!summary && !body && bullets.length === 0 && subsections.length === 0 && !table?.rows.length) {
    return null;
  }

  return {
    ...section,
    title,
    summary: summary ?? undefined,
    body: body ?? undefined,
    bullets: bullets.length ? bullets : undefined,
    subsections: subsections.length ? subsections : undefined,
    table:
      table && table.columns.length && table.rows.length
        ? table
        : null,
  };
}

export function controlledTbd() {
  return CONTROLLED_TBD;
}
