import { createClient } from "@supabase/supabase-js";

export const TERMS_VERSION = "v1.0";

export const CLICKWRAP_LABEL =
  "I agree to the Terms of Service, Liability Waiver, and Licensing Agreement";

export const DOWNLOAD_CONFIRMATION_LABEL =
  "I confirm I have reviewed and accept responsibility for this document";

export type UserAgreementRecord = {
  user_id: string;
  accepted_terms: boolean;
  accepted_at: string;
  ip_address: string | null;
  terms_version: string;
};

export function getClientIpAddress(request: Request) {
  const forwardedFor = request.headers.get("x-forwarded-for");
  if (forwardedFor) {
    return forwardedFor.split(",")[0]?.trim() || null;
  }

  const realIp = request.headers.get("x-real-ip");
  return realIp?.trim() || null;
}

export function buildAgreementAcceptance(params: {
  userId: string;
  ipAddress?: string | null;
  termsVersion?: string;
}) {
  return {
    user_id: params.userId,
    accepted_terms: true,
    accepted_at: new Date().toISOString(),
    ip_address: params.ipAddress ?? null,
    terms_version: params.termsVersion ?? TERMS_VERSION,
    updated_at: new Date().toISOString(),
  };
}

export async function getUserAgreementRecord(
  supabase: ReturnType<typeof createClient>,
  userId: string
) {
  const { data, error } = await supabase
    .from("user_agreements")
    .select("user_id, accepted_terms, accepted_at, ip_address, terms_version")
    .eq("user_id", userId)
    .maybeSingle<UserAgreementRecord>();

  return {
    data: data ?? null,
    error,
  };
}

export async function acceptUserAgreement(params: {
  supabase: ReturnType<typeof createClient>;
  userId: string;
  ipAddress?: string | null;
  termsVersion?: string;
}) {
  const payload = buildAgreementAcceptance(params);

  return params.supabase.from("user_agreements").upsert(payload, {
    onConflict: "user_id",
  });
}

export const AGREEMENT_SECTIONS = {
  termsOfService: {
    title: "Terms of Service, Licensing, and Platform Use",
    sections: [
      {
        heading: "License and No Resale",
        body:
          "By using SafetyDocs360, you agree that all generated documents and platform outputs are licensed, not sold. You may use them only for internal business purposes. You may not resell, redistribute, sublicense, share documents outside your organization, or use platform outputs to create competing products.",
      },
      {
        heading: "No Professional Advice",
        body:
          "SafetyDocs360 does not provide legal, engineering, or safety consulting. Nothing generated by the platform should be relied upon as legal, engineering, or professional safety advice. You agree to consult qualified professionals before implementation.",
      },
      {
        heading: "Account Abuse and Termination",
        body:
          "We reserve the right to suspend or terminate any account that violates these terms, including unauthorized sharing, resale, misuse of generated documents, or attempts to undermine the platform or its licensing protections.",
      },
      {
        heading: "Indemnification",
        body:
          "You agree to indemnify, defend, and hold harmless SafetyDocs360, its owners, operators, affiliates, employees, and contractors from any claims, damages, losses, liabilities, costs, or legal actions arising out of your use of the platform, your use of generated documents, or your failure to verify compliance and jobsite safety obligations.",
      },
    ],
  },
  liabilityWaiver: {
    title: "Liability Waiver and Assumption of Risk",
    sections: [
      {
        heading: "As-Is Platform and Outputs",
        body:
          "All documents, templates, forms, and generated outputs are provided on an as-is and as-available basis for informational purposes only. SafetyDocs360 makes no guarantees regarding accuracy, regulatory compliance, completeness, or safety effectiveness.",
      },
      {
        heading: "User Responsibility",
        body:
          "You assume full responsibility for jobsite safety, compliance with OSHA and all applicable laws, verification of document accuracy, and implementation of all procedures, controls, and protective measures referenced by the platform or generated documents.",
      },
      {
        heading: "Limitation of Liability",
        body:
          "SafetyDocs360 is not liable for injury, death, property damage, OSHA violations, regulatory actions, project delays, financial loss, or any other damages arising from use of the platform or generated documents. Use of the platform is entirely at your own risk.",
      },
    ],
  },
} as const;
