import type { SafetyObservationKpis, SafetyObservationRow } from "./types";

const now = new Date();
const iso = (d: Date) => d.toISOString();
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d;
};

export const MOCK_SAFETY_OBSERVATIONS: SafetyObservationRow[] = [
  {
    id: "00000000-0001-4000-8000-000000000001",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111101",
    project_id: null,
    title: "Unguarded floor opening — Level 3",
    description: "Opening left uncovered after material pass-through.",
    observation_type: "Hazard",
    category: "Working_at_Heights",
    subcategory: "Unprotected_Edges",
    severity: "High",
    status: "Open",
    trade: "Concrete",
    location: "Level 3 east wing",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: iso(daysAgo(-2)).slice(0, 10),
    closed_at: null,
    photo_urls: [],
    tags: [],
    corrective_action: "Install guardrails and covers per site plan.",
    immediate_action_taken: "Caution tape and signage placed.",
    created_at: iso(daysAgo(1)),
    updated_at: iso(daysAgo(1)),
  },
  {
    id: "00000000-0001-4000-8000-000000000002",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111101",
    project_id: null,
    title: "Extension cord run through standing water",
    description: null,
    observation_type: "Hazard",
    category: "Electrical_Safety",
    subcategory: "Damaged_Cords",
    severity: "Critical",
    status: "In Progress",
    trade: "Electrical",
    location: "Temp power skid",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: iso(daysAgo(-1)).slice(0, 10),
    closed_at: null,
    photo_urls: [],
    tags: [],
    corrective_action: "Reroute GFCI-protected feeds; remove damaged cord.",
    immediate_action_taken: "Power isolated at skid.",
    created_at: iso(daysAgo(2)),
    updated_at: iso(daysAgo(0)),
  },
  {
    id: "00000000-0001-4000-8000-000000000003",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111102",
    project_id: null,
    title: "Crew stopped work to reset barricade after wind event",
    description: null,
    observation_type: "Positive",
    category: "Safe_Behavior",
    subcategory: "Following_Plan",
    severity: "Low",
    status: "Closed",
    trade: "General",
    location: "North gate",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: null,
    closed_at: iso(daysAgo(3)),
    photo_urls: [],
    tags: [],
    corrective_action: null,
    immediate_action_taken: "Barricade re-secured before work resumed.",
    created_at: iso(daysAgo(5)),
    updated_at: iso(daysAgo(3)),
  },
  {
    id: "00000000-0001-4000-8000-000000000004",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111102",
    project_id: null,
    title: "Near miss — load swing over walkway",
    description: null,
    observation_type: "Near_Miss",
    category: "Indicators",
    subcategory: "High_Potential",
    severity: "High",
    status: "Open",
    trade: "Rigging",
    location: "Crane pick zone B",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: iso(daysAgo(-5)).slice(0, 10),
    closed_at: null,
    photo_urls: [],
    tags: [],
    corrective_action: "Update lift plan; tag line and spotter required.",
    immediate_action_taken: "Lift halted; walkway cleared.",
    created_at: iso(daysAgo(4)),
    updated_at: iso(daysAgo(4)),
  },
  {
    id: "00000000-0001-4000-8000-000000000005",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: null,
    project_id: null,
    title: "Housekeeping excellent in laydown yard",
    description: null,
    observation_type: "Positive",
    category: "Safe_Behavior",
    subcategory: "Good_Housekeeping",
    severity: "Low",
    status: "Closed",
    trade: "Logistics",
    location: "Laydown A",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: null,
    closed_at: iso(daysAgo(1)),
    photo_urls: [],
    tags: [],
    corrective_action: null,
    immediate_action_taken: null,
    created_at: iso(daysAgo(6)),
    updated_at: iso(daysAgo(1)),
  },
  {
    id: "00000000-0001-4000-8000-000000000006",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111101",
    project_id: null,
    title: "Missing guard on table saw",
    description: null,
    observation_type: "Hazard",
    category: "Equipment_Tools",
    subcategory: "Missing_Guards",
    severity: "Medium",
    status: "Closed",
    trade: "Carpentry",
    location: "Fab shop",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: null,
    closed_at: iso(daysAgo(2)),
    photo_urls: [],
    tags: [],
    corrective_action: "OEM guard reinstalled; competency check.",
    immediate_action_taken: "Tool tagged out.",
    created_at: iso(daysAgo(8)),
    updated_at: iso(daysAgo(2)),
  },
  {
    id: "00000000-0001-4000-8000-000000000007",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111103",
    project_id: null,
    title: "Worker observed 100% PPE on elevated work",
    description: null,
    observation_type: "Positive",
    category: "Safe_Behavior",
    subcategory: "Proper_PPE",
    severity: "Low",
    status: "Open",
    trade: "Steel",
    location: "Tower crane deck",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: null,
    closed_at: null,
    photo_urls: [],
    tags: [],
    corrective_action: null,
    immediate_action_taken: null,
    created_at: iso(daysAgo(0)),
    updated_at: iso(daysAgo(0)),
  },
  {
    id: "00000000-0001-4000-8000-000000000008",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111103",
    project_id: null,
    title: "Slip hazard — ice on access stairs",
    description: null,
    observation_type: "Hazard",
    category: "Work_Environment",
    subcategory: "Slip_Trip_Hazards",
    severity: "Medium",
    status: "In Progress",
    trade: "General",
    location: "Stair tower 2",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: iso(daysAgo(-1)).slice(0, 10),
    closed_at: null,
    photo_urls: [],
    tags: [],
    corrective_action: "De-ice and grit; daily inspection checklist.",
    immediate_action_taken: "Salt applied; warning signs posted.",
    created_at: iso(daysAgo(1)),
    updated_at: iso(daysAgo(0)),
  },
  {
    id: "00000000-0001-4000-8000-000000000009",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111101",
    project_id: null,
    title: "Hot work permit not posted at job board",
    description: null,
    observation_type: "Hazard",
    category: "Permits_Compliance",
    subcategory: "Missing_Permit",
    severity: "High",
    status: "Open",
    trade: "Pipe",
    location: "Welding bay",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: iso(daysAgo(0)).slice(0, 10),
    closed_at: null,
    photo_urls: [],
    tags: [],
    corrective_action: "Post permit; verify fire watch assigned.",
    immediate_action_taken: "Welding stopped until permit visible.",
    created_at: iso(daysAgo(2)),
    updated_at: iso(daysAgo(2)),
  },
  {
    id: "00000000-0001-4000-8000-00000000000a",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111102",
    project_id: null,
    title: "First aid — minor cut bandaged on site",
    description: null,
    observation_type: "Near_Miss",
    category: "Indicators",
    subcategory: "First_Aid",
    severity: "Low",
    status: "Closed",
    trade: "General",
    location: "Site trailer",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: null,
    closed_at: iso(daysAgo(4)),
    photo_urls: [],
    tags: [],
    corrective_action: "Refresher on glove use when handling banding.",
    immediate_action_taken: "First aid kit used; supervision notified.",
    created_at: iso(daysAgo(5)),
    updated_at: iso(daysAgo(4)),
  },
  {
    id: "00000000-0001-4000-8000-00000000000b",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111101",
    project_id: null,
    title: "Forklift speed in congested area",
    description: null,
    observation_type: "Hazard",
    category: "Material_Handling_Rigging",
    subcategory: "Forklift_Operation",
    severity: "Medium",
    status: "Open",
    trade: "Material handling",
    location: "Delivery lane",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: iso(daysAgo(-3)).slice(0, 10),
    closed_at: null,
    photo_urls: [],
    tags: [],
    corrective_action: "Coach operator; enforce 5 mph zone.",
    immediate_action_taken: "Supervisor discussion same shift.",
    created_at: iso(daysAgo(3)),
    updated_at: iso(daysAgo(3)),
  },
  {
    id: "00000000-0001-4000-8000-00000000000c",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111103",
    project_id: null,
    title: "Toolbox talk on LOTO well delivered",
    description: null,
    observation_type: "Positive",
    category: "Safe_Behavior",
    subcategory: "Leadership_Involvement",
    severity: "Low",
    status: "Closed",
    trade: "Maintenance",
    location: "Mechanical yard",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: null,
    closed_at: iso(daysAgo(6)),
    photo_urls: [],
    tags: [],
    corrective_action: null,
    immediate_action_taken: null,
    created_at: iso(daysAgo(7)),
    updated_at: iso(daysAgo(6)),
  },
  {
    id: "00000000-0001-4000-8000-00000000000d",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111102",
    project_id: null,
    title: "Confined space attendant stepped away briefly",
    description: null,
    observation_type: "Hazard",
    category: "High_Risk_Work",
    subcategory: "Confined_Space",
    severity: "Critical",
    status: "In Progress",
    trade: "Confined space team",
    location: "Tank T-4",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: iso(daysAgo(-1)).slice(0, 10),
    closed_at: null,
    photo_urls: [],
    tags: [],
    corrective_action: "Re-train attendants; add secondary verifier.",
    immediate_action_taken: "Entry paused; attendant returned.",
    created_at: iso(daysAgo(2)),
    updated_at: iso(daysAgo(1)),
  },
  {
    id: "00000000-0001-4000-8000-00000000000e",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111101",
    project_id: null,
    title: "Noise exposure — grinder without hearing protection nearby",
    description: null,
    observation_type: "Hazard",
    category: "Work_Environment",
    subcategory: "Noise_Exposure",
    severity: "Medium",
    status: "Closed",
    trade: "Ironwork",
    location: "South staging",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: null,
    closed_at: iso(daysAgo(5)),
    photo_urls: [],
    tags: [],
    corrective_action: "Rotate tasks; hearing protection zone signage.",
    immediate_action_taken: "Workers moved to safe distance.",
    created_at: iso(daysAgo(9)),
    updated_at: iso(daysAgo(5)),
  },
  {
    id: "00000000-0001-4000-8000-00000000000f",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: null,
    project_id: null,
    title: "Unsafe condition — staging overload",
    description: null,
    observation_type: "Near_Miss",
    category: "Indicators",
    subcategory: "Unsafe_Condition",
    severity: "High",
    status: "Open",
    trade: "Scaffold",
    location: "West facade",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: iso(daysAgo(-4)).slice(0, 10),
    closed_at: null,
    photo_urls: [],
    tags: [],
    corrective_action: "Engineer review load chart; redistribute materials.",
    immediate_action_taken: "Loading stopped.",
    created_at: iso(daysAgo(3)),
    updated_at: iso(daysAgo(3)),
  },
  {
    id: "00000000-0001-4000-8000-000000000010",
    company_id: "00000000-0000-4000-8000-000000000099",
    jobsite_id: "11111111-1111-4111-8111-111111111103",
    project_id: null,
    title: "Strong communication during crane critical lift",
    description: null,
    observation_type: "Positive",
    category: "Safe_Behavior",
    subcategory: "Strong_Communication",
    severity: "Low",
    status: "Closed",
    trade: "Crane",
    location: "Pick zone A",
    linked_dap_id: null,
    linked_jsa_id: null,
    linked_incident_id: null,
    assigned_to: null,
    created_by: null,
    closed_by: null,
    due_date: null,
    closed_at: iso(daysAgo(7)),
    photo_urls: [],
    tags: [],
    corrective_action: null,
    immediate_action_taken: null,
    created_at: iso(daysAgo(8)),
    updated_at: iso(daysAgo(7)),
  },
];

export function computeKpisFromRows(rows: SafetyObservationRow[]): SafetyObservationKpis {
  const startOfWeek = new Date(now);
  const day = startOfWeek.getDay();
  const diff = startOfWeek.getDate() - day + (day === 0 ? -6 : 1);
  startOfWeek.setDate(diff);
  startOfWeek.setHours(0, 0, 0, 0);

  let openHazards = 0;
  let highCriticalOpen = 0;
  let positiveObservations = 0;
  let nearMisses = 0;
  let closedThisWeek = 0;

  for (const r of rows) {
    if (r.observation_type === "Positive") positiveObservations += 1;
    if (r.observation_type === "Near_Miss") nearMisses += 1;
    if (r.observation_type === "Hazard" && r.status !== "Closed") openHazards += 1;
    if (
      r.status !== "Closed" &&
      (r.severity === "High" || r.severity === "Critical")
    ) {
      highCriticalOpen += 1;
    }
    if (r.closed_at) {
      const c = new Date(r.closed_at);
      if (c >= startOfWeek) closedThisWeek += 1;
    }
  }

  return {
    totalObservations: rows.length,
    openHazards,
    highCriticalOpen,
    positiveObservations,
    nearMisses,
    closedThisWeek,
  };
}

export const MOCK_SAFETY_KPIS = computeKpisFromRows(MOCK_SAFETY_OBSERVATIONS);
