import type { GusPlanModule } from "@/lib/gus/plans/basePlanningTypes";

export const generalPreTask: GusPlanModule = {
  moduleId: "generalPreTask",
  displayName: "General Daily Pre-Task Planning",
  description: "Universal daily planning for routine and non-routine field work before the crew starts.",
  triggerKeywords: [
    "pre-task",
    "pretask",
    "daily plan",
    "daily briefing",
    "toolbox",
    "general work",
    "field work",
    "crew briefing",
    "task planning",
    "job briefing",
  ],
  requiredQuestions: [
    "What work is being performed?",
    "Where is the work being performed?",
    "Who is performing the work and who is leading the crew?",
    "What equipment, tools, materials, chemicals, or energy sources are involved?",
    "What hazards are expected before work starts?",
    "What controls are required and who owns them?",
    "What permits, inspections, or training may require review?",
    "What changed since the last plan or shift?",
    "What stop-work triggers apply?",
    "Who must review this draft plan before work starts?",
  ],
  hazardCategories: [
    "Line of fire",
    "Slip, trip, and fall",
    "Manual handling",
    "Mobile equipment interface",
    "Stored energy",
    "Weather or changing conditions",
    "Housekeeping and access",
    "Simultaneous operations",
  ],
  commonControls: [
    "Draft task sequence for supervisor review",
    "Crew pre-task briefing with questions encouraged",
    "Work-zone control, barricades, or spotter review when exposure exists",
    "Housekeeping and access route verification",
    "Permit, training, and inspection review against company policy",
    "Stop-work triggers discussed before work starts",
    "Emergency access and communication check",
  ],
  possiblePermits: [
    "Site-specific permit review",
    "Hot work, confined space, excavation, LOTO, lift, or work-at-height permit may require review based on task details",
  ],
  possibleTrainingRequirements: [
    "Site orientation",
    "Task-specific training",
    "Equipment authorization when equipment is used",
    "Hazard communication when chemicals or materials are involved",
  ],
  requiredReviewRoles: ["Supervisor review required", "Authorized safety representative review may be required"],
  stopWorkTriggers: [
    "Scope changes from the draft plan",
    "A hazard is discovered that was not discussed",
    "Required permit, training, inspection, or reviewer is missing",
    "Crew members are unsure about the task or controls",
    "Weather, access, equipment, or simultaneous operations change risk",
  ],
  draftPlanSections: [
    "Draft task summary",
    "Crew and supervisor review",
    "Known hazards",
    "Draft controls",
    "Missing information",
    "Permits, training, and inspections to verify",
    "Stop-work triggers",
    "Emergency response considerations",
    "Human review requirements",
  ],
  validationRules: [
    {
      id: "general_pre_task_human_review",
      description: "Draft only: identify the supervisor or authorized reviewer before work starts.",
      severity: "warning",
    },
    {
      id: "general_pre_task_missing_task_scope",
      description: "Missing information: task scope, location, crew, hazards, controls, or stop-work triggers require follow-up.",
      severity: "warning",
    },
    {
      id: "general_pre_task_no_official_record",
      description: "Gus may draft recommendations only; official records are not created by this module.",
      severity: "info",
    },
  ],
};
