import type { GusPlanModule } from "@/lib/gus/plans/basePlanningTypes";

export const hotWork: GusPlanModule = {
  moduleId: "hotWork",
  displayName: "Hot Work",
  description: "Draft planning for welding, cutting, grinding, brazing, torch work, or other spark-producing activity.",
  triggerKeywords: [
    "hot work",
    "weld",
    "welding",
    "cut",
    "cutting",
    "grind",
    "grinding",
    "torch",
    "brazing",
    "solder",
    "spark",
    "fire watch",
  ],
  requiredQuestions: [
    "What hot work activity is planned?",
    "Where will the hot work occur and what is nearby?",
    "What combustible materials, coatings, residues, or openings are present?",
    "How will combustibles be removed, shielded, wetted, or otherwise controlled?",
    "Who is assigned as fire watch and how long will monitoring continue?",
    "What fire protection equipment is staged and inspected?",
    "Is atmospheric monitoring needed based on the area, material, or company policy?",
    "What ventilation or fume controls are needed?",
    "Who must verify the draft permit or checklist before work starts?",
  ],
  hazardCategories: [
    "Fire or smoldering material",
    "Burns",
    "Fumes and smoke",
    "Combustible exposure",
    "Flammable atmosphere concern",
    "Cylinder or fuel gas handling",
    "Adjacent-space exposure",
  ],
  commonControls: [
    "Draft hot work permit checklist for supervisor review",
    "Combustible removal, shielding, or wet-down verified before work",
    "Fire watch assignment verified against company policy",
    "Fire extinguisher or fire protection equipment staged and inspected",
    "Ventilation or fume control reviewed before work",
    "Atmospheric monitoring reviewed when conditions indicate it may be needed",
    "Post-work fire watch or area monitoring reviewed with the supervisor",
  ],
  possiblePermits: [
    "Hot work permit may require review",
    "Confined space permit may require review if hot work occurs in or near a confined space",
    "Fire system impairment review may be needed if protection systems are affected",
  ],
  possibleTrainingRequirements: [
    "Hot work training",
    "Fire watch training",
    "Extinguisher use briefing",
    "Hazard communication when coatings, residues, or fumes are involved",
  ],
  requiredReviewRoles: ["Supervisor review required", "Authorized safety representative review may be required"],
  stopWorkTriggers: [
    "Combustibles are not removed or controlled",
    "Fire watch is not assigned when required by company policy",
    "Fire protection equipment is missing or not ready",
    "Atmospheric conditions are unknown where flammable or oxygen concerns may exist",
    "Ventilation is inadequate for fumes or smoke",
    "Sparks, heat, or slag can affect adjacent spaces not included in the draft plan",
  ],
  draftPlanSections: [
    "Draft hot work scope",
    "Area and adjacent-space review",
    "Combustible control plan",
    "Fire watch plan",
    "Fire protection equipment",
    "Ventilation and fume controls",
    "Missing information",
    "Supervisor review requirements",
  ],
  validationRules: [
    {
      id: "hot_work_fire_watch",
      description: "Draft only: identify fire watch needs and fire protection for supervisor review.",
      severity: "warning",
    },
    {
      id: "hot_work_missing_combustible_review",
      description: "Missing information: combustibles, adjacent spaces, and fire protection readiness require follow-up.",
      severity: "critical",
    },
    {
      id: "hot_work_verify_company_policy",
      description: "Verify permit and monitoring requirements against company policy before work starts.",
      severity: "warning",
    },
  ],
};
