import type { GusPlanModule } from "@/lib/gus/plans/basePlanningTypes";

export const loto: GusPlanModule = {
  moduleId: "loto",
  displayName: "LOTO / Stored Energy",
  description: "Draft planning for energy isolation, stored energy control, and restart prevention.",
  triggerKeywords: [
    "loto",
    "lockout",
    "tagout",
    "lock out",
    "tag out",
    "isolation",
    "stored energy",
    "zero energy",
    "de-energize",
    "maintenance",
    "unexpected startup",
  ],
  requiredQuestions: [
    "What equipment, process, or system is being worked on?",
    "What electrical, mechanical, hydraulic, pneumatic, thermal, chemical, gravity, or stored energy sources are involved?",
    "How will each energy source be isolated?",
    "How will stored energy be released, blocked, restrained, or controlled?",
    "How will zero energy or safe state be verified before work starts?",
    "Who controls the locks, tags, or isolation devices?",
    "What restart, handoff, or shift-change controls are needed?",
    "Who must review the draft isolation plan before work starts?",
  ],
  hazardCategories: [
    "Unexpected startup",
    "Stored energy release",
    "Electrical energy",
    "Mechanical energy",
    "Hydraulic or pneumatic pressure",
    "Gravity or suspended load",
    "Thermal or chemical energy",
  ],
  commonControls: [
    "Draft energy source list for qualified or authorized review",
    "Isolation method documented for each identified source",
    "Stored energy release, block, bleed, or restraint method reviewed",
    "Lock, tag, or isolation device control verified against company policy",
    "Try-start or verification step included before work starts",
    "Restart and handoff controls documented for review",
    "Affected workers briefed before work begins",
  ],
  possiblePermits: [
    "LOTO permit or checklist may require review",
    "Energized electrical work permit may require review if de-energizing is not feasible",
    "Line break or stored pressure checklist may require review based on task details",
  ],
  possibleTrainingRequirements: [
    "Authorized employee LOTO training",
    "Affected employee briefing",
    "Qualified person review when electrical energy is involved",
    "Equipment-specific isolation procedure training when required by company policy",
  ],
  requiredReviewRoles: ["Authorized employee review required", "Supervisor review required", "Qualified person review required when electrical energy is involved"],
  stopWorkTriggers: [
    "An energy source is unknown or not listed",
    "Isolation point cannot be verified",
    "Stored energy release method is unclear",
    "Zero-energy verification is not completed",
    "Lock or tag control is unclear",
    "Scope changes or additional equipment is discovered",
  ],
  draftPlanSections: [
    "Draft equipment and scope",
    "Energy source inventory",
    "Isolation methods",
    "Stored energy controls",
    "Verification steps",
    "Lock and tag control",
    "Missing information",
    "Human review requirements",
  ],
  validationRules: [
    {
      id: "loto_zero_energy",
      description: "Draft only: include isolation and verification steps for authorized review.",
      severity: "critical",
    },
    {
      id: "loto_missing_energy_inventory",
      description: "Missing information: energy source inventory, isolation method, and verification method require follow-up.",
      severity: "critical",
    },
    {
      id: "loto_no_release_language",
      description: "Gus may not release equipment for work; human review is required before work starts.",
      severity: "critical",
    },
  ],
};
