import type { GusPlanModule } from "@/lib/gus/plans/basePlanningTypes";

export const trenching: GusPlanModule = {
  moduleId: "trenching",
  displayName: "Trenching / Excavation",
  description: "Draft planning for trenching, excavation, ground disturbance, and work near excavations.",
  triggerKeywords: [
    "trench",
    "trenching",
    "excavation",
    "excavate",
    "dig",
    "ground disturbance",
    "soil",
    "shoring",
    "benching",
    "sloping",
    "utility locate",
    "spoil pile",
  ],
  requiredQuestions: [
    "What is the excavation or trench location, depth, length, and purpose?",
    "Have underground utilities and nearby structures been reviewed?",
    "Who is the competent person for excavation review?",
    "What soil, water, vibration, traffic, or adjacent load conditions could affect stability?",
    "What protective system or setback approach may be required?",
    "What access and egress will be provided?",
    "How will spoil piles, equipment, and pedestrian or vehicle traffic be controlled?",
    "What inspections are required before entry and as conditions change?",
    "What emergency response or rescue considerations apply?",
  ],
  hazardCategories: [
    "Cave-in or soil movement",
    "Underground utility strike",
    "Mobile equipment or struck-by exposure",
    "Water accumulation",
    "Hazardous atmosphere concern",
    "Adjacent structure or surcharge load",
    "Access and egress limitation",
    "Public or pedestrian interface",
  ],
  commonControls: [
    "Draft excavation plan for competent person review",
    "Utility locate and verification reviewed before digging",
    "Protective system, slope, bench, shield, or shore approach verified against company policy",
    "Access and egress plan reviewed before entry",
    "Spoil pile, equipment, and surcharge setback reviewed",
    "Water, atmosphere, vibration, and changing condition monitoring",
    "Barricades, traffic control, and pedestrian protection",
    "Documented inspection before entry and after changing conditions",
  ],
  possiblePermits: [
    "Excavation permit may require review",
    "Utility permit or locate documentation may require review",
    "Confined space review may be required if excavation conditions indicate restricted entry or atmospheric concern",
    "Traffic control permit or plan may require review when public or vehicle interface exists",
  ],
  possibleTrainingRequirements: [
    "Excavation awareness",
    "Competent person training",
    "Utility damage prevention briefing",
    "Traffic control or spotter briefing when equipment or vehicles are present",
  ],
  requiredReviewRoles: ["Competent person review required", "Supervisor review required"],
  stopWorkTriggers: [
    "Utility conflict, unknown utility, or locate mismatch",
    "Soil movement, cracking, sloughing, or cave-in indication",
    "Water accumulation or changing weather affects excavation stability",
    "Protective system, access, or egress is missing or not verified",
    "Atmospheric concern or unusual odor is present",
    "Spoil pile, equipment, traffic, or adjacent load creates unreviewed exposure",
    "Competent person review has not occurred",
  ],
  draftPlanSections: [
    "Draft excavation scope",
    "Location, depth, and purpose",
    "Utilities and adjacent structures",
    "Soil, water, and changing conditions",
    "Protective system review",
    "Access and egress",
    "Spoil, equipment, and traffic controls",
    "Inspection requirements",
    "Missing information",
    "Competent person and supervisor review",
  ],
  validationRules: [
    {
      id: "trenching_competent_person",
      description: "Draft only: identify competent person review before excavation entry or work near the excavation.",
      severity: "critical",
    },
    {
      id: "trenching_missing_utility_review",
      description: "Missing information: utility review, depth, protective system, access, and inspection plan require follow-up.",
      severity: "critical",
    },
    {
      id: "trenching_verify_company_policy",
      description: "Verify permits, inspections, and protective system requirements against company policy before work starts.",
      severity: "warning",
    },
  ],
};

