import type { GusPlanModule } from "@/lib/gus/plans/basePlanningTypes";

export const workAtHeight: GusPlanModule = {
  moduleId: "workAtHeight",
  displayName: "Work at Height",
  description: "Draft planning for elevated work involving fall exposure, edges, roofs, ladders, lifts, or scaffolds.",
  triggerKeywords: [
    "height",
    "heights",
    "fall",
    "fall protection",
    "roof",
    "edge",
    "elevated",
    "harness",
    "anchor",
    "lifeline",
    "ladder",
    "scaffold",
    "lift",
  ],
  requiredQuestions: [
    "What work at height is being performed and at what location?",
    "What fall exposure exists, including edges, openings, ladders, lifts, scaffolds, or roofs?",
    "What access method will be used and has it been inspected?",
    "What guardrail, anchor, restraint, arrest, or positioning system may be required?",
    "How will dropped objects be controlled?",
    "What weather, surface, or overhead conditions could change risk?",
    "What rescue or retrieval plan applies if a fall occurs?",
    "Who must complete competent person or supervisor review before work starts?",
  ],
  hazardCategories: [
    "Fall from elevation",
    "Dropped object",
    "Unprotected edge or opening",
    "Ladder, lift, or scaffold access",
    "Fragile or unstable surface",
    "Weather exposure",
    "Suspension trauma or delayed rescue",
  ],
  commonControls: [
    "Draft fall protection approach for competent person review",
    "Access equipment inspection before use",
    "Anchor, guardrail, restraint, or arrest system verified against company policy",
    "Dropped object prevention such as tool control, exclusion zone, or barricade",
    "Weather and surface condition check before elevated work",
    "Rescue or retrieval plan reviewed before work starts",
    "Crew briefing on edges, openings, access limits, and stop-work triggers",
  ],
  possiblePermits: [
    "Work at height permit may require review",
    "Lift or scaffold permit/tag review may be required by company policy",
    "Roof access review may be required based on site procedure",
  ],
  possibleTrainingRequirements: [
    "Fall protection training",
    "Harness inspection and use briefing",
    "MEWP, ladder, or scaffold training based on access method",
    "Rescue plan briefing when fall arrest is used",
  ],
  requiredReviewRoles: ["Competent person review required", "Supervisor review required"],
  stopWorkTriggers: [
    "Fall protection system is missing, damaged, or not verified",
    "Access method is unstable, damaged, or not inspected",
    "Anchor or guardrail adequacy is unknown",
    "Dropped object exposure is uncontrolled",
    "Weather, wind, rain, lightning, or surface conditions make elevated work unsafe",
    "Rescue plan is missing when fall arrest is used",
  ],
  draftPlanSections: [
    "Draft elevated work scope",
    "Access method",
    "Fall exposure",
    "Fall protection controls",
    "Dropped object controls",
    "Weather and surface conditions",
    "Rescue considerations",
    "Missing information",
    "Competent person or supervisor review",
  ],
  validationRules: [
    {
      id: "height_rescue_review",
      description: "Draft only: include rescue considerations and competent person or supervisor review.",
      severity: "warning",
    },
    {
      id: "height_missing_fall_exposure",
      description: "Missing information: fall exposure, access method, fall protection approach, and rescue plan require follow-up.",
      severity: "critical",
    },
    {
      id: "height_verify_company_policy",
      description: "Verify permit, inspection, and training requirements against company policy before work starts.",
      severity: "warning",
    },
  ],
};
